### ISSUE TITLE
Provide TypeScript version

### ISSUE THREAD

**Issue by rajeevkumarsharma** [driftyco/ionic-conference-app#109]
Pls update typescript version as you update JS version

**Comment by brandyscarney** [comment]
We are trying to keep the TypeScript version up-to-date with the JS version but sometimes things come up or things break and we have to shift our focus. If it is significantly behind the JS, I recommend joining our Slack channel and letting us know there: http://ionicworldwide.herokuapp.com/

**Comment by mashaly100200** [comment]
@rajeevkumarsharma  , @brandyscarney   where is typescript version ?

plz ionic team focus on typescript i think most developer who use angular2 will shift to typescript 


thanks ionc team

**Comment by brandyscarney** [comment]
The typescript version is on the `typescript` branch: https://github.com/driftyco/ionic-conference-app/tree/typescript

**Comment by mashaly100200** [comment]
@brandyscarney  many thanks   :+1:
