### ISSUE TITLE
Use a standard for folder structure

### ISSUE THREAD

**Issue by rajeevkumarsharma** [driftyco/ionic-conference-app#110]

**Comment by 3dd13** [comment]
what do you expect for this issue ?

there was an another issue discussing the new folder structure design:
https://github.com/driftyco/ionic-conference-app/issues/98

there were some commits yesterday on implementing the design
https://github.com/driftyco/ionic-conference-app/commit/2be9ca212d74beb82af64982f01ea2f487dc1428

**Comment by rajeevkumarsharma** [comment]
We should go with ionic default

**Comment by 3dd13** [comment]
do you mean the app folder outside www ?
https://github.com/driftyco/ionic-conference-app/issues/98 is the new default
the core ionic-cli had already updated to follow this new folder structure

**Comment by rajeevkumarsharma** [comment]
We should use app folder which is good for performance and ease of use.
#98
It has directive folder, there is no such thing in angular2. It's all components.

so, I success

- app
    - components
        - about
            - about.js
            - about.scss
            - about.html
        - contact
            - contact.js
            - contact.scss
            - contact.html
    - providers/services
         - about
             - about-provider.js


Placing app folder inside/outside may depends on offline template compiling.

**Comment by brandyscarney** [comment]
Directives do exist in Angular 2: https://angular.io/docs/ts/latest/api/core/Directive-var.html

**Comment by brandyscarney** [comment]
Closing this. #98 is how the directory structure will be set by default, any opinions on it can go there. Thanks.
