### ISSUE TITLE
Add a busy indicator as app loaded

### ISSUE THREAD

**Issue by rajeevkumarsharma** [driftyco/ionic-conference-app#113]
1. Pls add busy indicator when we open app till app is fully loaded.

**Comment by 3dd13** [comment]
* what kind of Ionic feature you want to demonstrate with this "busy indicator" ?

@rajeevkumarsharma try to implement it and submit a pull request

**Comment by rajeevkumarsharma** [comment]
App Launch SplashScreen feature of ionic

**Comment by brandyscarney** [comment]
Added splash screen as a task for this issue: https://github.com/driftyco/ionic-conference-app/issues/54
