### ISSUE TITLE
error on ionic serve 

### ISSUE THREAD

**Issue by jvaranam** [driftyco/ionic-conference-app#115]
Clone this repository.
Run npm install from the project root.
Install the ionic CLI (npm install -g ionic@beta)  -- my version 2.0.0-beta.12
Run ionic serve in a terminal from the project root.

ionic serve throws the following error on chrome console. plz help me to fix

GET http://localhost:8100/build/css/app.ios.css 404 (Not Found)setupDom @ app.bundle.js:3378ionicProviders @ app.bundle.js:3343(anonymous function) @ app.bundle.js:59155(anonymous function) @ app.bundle.js:3233__webpack_require__ @ app.bundle.js:20(anonymous function) @ app.bundle.js:51__webpack_require__ @ app.bundle.js:20(anonymous function) @ app.bundle.js:40(anonymous function) @ app.bundle.js:43
app.bundle.js:34123 GET http://localhost:8100/build/app.html 404 (Not Found)

**Comment by brandyscarney** [comment]
Does the `build` folder exist under `www`?: `ionic-conference-app/www/build`

And when you run `ionic serve` do you see this or any errors in the terminal?:

```
$ ionic serve

∆ Compiling and bundling with Webpack...
√ Using your webpack.config.js file

∆ Compiling Sass to CSS
√ Matching patterns: app/app.+(ios|md).scss

∆ Copying fonts
√ Matching patterns: node_modules/ionic-framework/fonts/**/*.ttf

∆ Copying HTML
√ Matching patterns: app/**/*.html

√ Sass compilation complete
√ Fonts copied to www/build/fonts
√ HTML copied to www/build

Hash: 2713b9a36c41269a4d61
Version: webpack 1.12.9
Time: 5602ms
        Asset     Size  Chunks             Chunk Names
app.bundle.js  2.58 MB       0  [emitted]  main
   [0] multi main 76 bytes {0} [built]
    + 363 hidden modules

√ Webpack complete

∆ Starting dev server.
```

**Comment by brandyscarney** [comment]
Also can you try updating to the latest beta CLI and see if that fixes it?

```
Ionic CLI Version: 2.0.0-beta.15
```

**Comment by rido-min** [comment]
I'm having the same error. In the webpack output I don't see 

∆ Copying HTML
√ Matching patterns: app/**/*.html

So, I don't have a www/build folder

**Comment by brandyscarney** [comment]
Can you print your `ionic info` please

**Comment by rido-min** [comment]
I updated to latest ionic@beta (2.0.0-beta.15) and not it works.

BTW here is my ```ionic info```

Your system information:

Cordova CLI: 5.2.0
Gulp version:  CLI version 3.9.0
Gulp local:
Ionic Version: 2.0.0-alpha.45
Ionic CLI Version: 2.0.0-beta.15
Ionic App Lib Version: 2.0.0-beta.8
OS: Windows 8.1
Node Version: v0.12.2

**Comment by brandyscarney** [comment]
Thanks, glad upgrading the CLI works!

**Comment by jvaranam** [comment]
Thanks Brandy,
After updating the Ionic CLI Version to 2.0.0-beta.15, which is working fine.

**Comment by brandyscarney** [comment]
Glad that fixed it!

**Comment by abdshomad** [comment]
Hi, I have the same error reported here. 

Here's my ionic info: 

vagrant@ionic-android:/vagrant_data/ionic-conference-app-PLAY$ ionic info

Your system information:

Cordova CLI: 5.1.1
Gulp version:  CLI version 3.9.0
Gulp local:
Ionic CLI Version: 2.0.0-beta.17
Ionic App Lib Version: 2.0.0-beta.8
OS: Distributor ID:     Ubuntu Description:     Ubuntu 14.04.1 LTS
Node Version: v0.12.7

Using inspect, web browser reported this file as not exist (404):  http://192.168.33.10:8100/build/js/app.bundle.js

Steps: 
Step 1: "npm install -g ionic@beta"
Step 2: "ionic serve"

**Comment by brandyscarney** [comment]
@abdshomad Did you run `npm install` from the root of the project after downloading it?

**Comment by yasirdev** [comment]
Hey @brandyscarney, I cloned the repository from
"https://github.com/driftyco/ionic-conference-app", as I just cloned it and run command
ionic serve this shows me an error i.e: 

Error: ENOENT: no such file or directory, open '/Users/Projects/ionic-conference-app/www/index.html

Please help as I want to develop with ionic 2.

ionic --version: 2.1.1
node -v:  v6.9.1
cordova -v: 6.3.1

**Comment by brandyscarney** [comment]
@yasirdev Could you run the following commands and paste the output please:

```
ionic info
npm -v
```

Make sure npm is version 3.x. To update, follow the steps [here](https://docs.npmjs.com/getting-started/installing-node#updating-npm).
