### ISSUE TITLE
ERR_FILE_NOT_FOUND

### ISSUE THREAD

**Issue by maxsay** [driftyco/ionic-conference-app#116]
ionic build successfully.
After installing the app my device I'm getting this error after debugging it

Failed to load resource: net::ERR_FILE_NOT_FOUND file:///build/app.html

I've check platforms\android\assets\www\build folder it contains the app.html file

**Comment by brandyscarney** [comment]
When was the last time you got the latest conference code? I fixed this error about 6 hours ago.

**Comment by maxsay** [comment]
Thanks it worked after using latest conference code.

**Comment by brandyscarney** [comment]
Awesome. :+1:
