### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 (Not Found)

### ISSUE THREAD

**Issue by chenzhizhuan** [driftyco/ionic-conference-app#117]
The build folder is not exist under www, And when I run ionic serve, see this in the terminal:
CengcengtekiMacBook-Air:www cengceng$ ionic serve
Running live reload server: undefined
Watching: 0=www/**/*, 1=!www/lib/**/*
√ Running dev server:  http://localhost:8100
Ionic server commands, enter:
  restart or r to restart the client app from the root
  goto or g and a url to have the app navigate to the given url
  consolelogs or c to enable/disable console log output
  serverlogs or s to enable/disable server log output
  quit or q to shutdown the server and exit

**Comment by chenzhizhuan** [comment]
CengcengtekiMacBook-Air:app cengceng$ ionic info

Your system information:

Cordova CLI: 4.3.0
Gulp version:  CLI version 3.9.0
Gulp local:  
Ionic CLI Version: 2.0.0-beta.15
Ionic App Lib Version: 2.0.0-beta.8
ios-deploy version: 1.8.3 
ios-sim version: 4.1.1 
OS: Mac OS X El Capitan
Node Version: v0.12.7
Xcode version: Xcode 6.4 Build version 6E35b

**Comment by arthurbragaa** [comment]
Hi @chenzhizhuan 
I managed to solve this issue running npm install from the project base folder.

**Comment by brandyscarney** [comment]
@chenzhizhuan Can you see if running `npm install` fixes it for you, too?

**Comment by chenzhizhuan** [comment]
CengcengtekiMacBook-Air:ionic-conference-app cengceng$ sudo npm install -g ionic@beta
Password:
/usr/local/bin/ionic -> /usr/local/lib/node_modules/ionic/bin/ionic

> ionic@2.0.0-beta.15 postinstall /usr/local/lib/node_modules/ionic
> node lib/tasks/postinstall


> spawn-sync@1.0.14 postinstall /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/cross-spawn/node_modules/spawn-sync
> node postinstall


> node-sass@3.4.2 install /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/gulp-sass/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/gulp-sass/node_modules/node-sass/vendor/darwin-x64-14/binding.node

> node-sass@3.4.2 postinstall /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/gulp-sass/node_modules/node-sass
> node scripts/build.js

` /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/gulp-sass/node_modules/node-sass/vendor/darwin-x64-14/binding.node ` exists. 
 testing binary.
Binary is fine; exiting.

> fsevents@1.0.6 install /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/gulp-watch/node_modules/chokidar/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success: "/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/gulp-watch/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v14-darwin-x64/fse.node" is installed via remote

> fsevents@1.0.6 install /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success: "/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v14-darwin-x64/fse.node" is installed via remote
spawn-sync@1.0.14 /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/cross-spawn/node_modules/spawn-sync
node-sass@3.4.2 /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/gulp-sass/node_modules/node-sass
fsevents@1.0.6 /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/gulp-watch/node_modules/chokidar/node_modules/fsevents
fsevents@1.0.6 /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents
ionic@2.0.0-beta.15 /usr/local/lib/node_modules/ionic
CengcengtekiMacBook-Air:ionic-conference-app cengceng$

**Comment by brandyscarney** [comment]
Can you try running just `npm install` from within the project folder? These steps: https://github.com/driftyco/ionic-conference-app#getting-started

**Comment by Ionitron** [comment]
Greetings @chenzhizhuan!

I'm sorry, but my sensors indicate that this issue may no longer apply to recent versions of Ionic.

If you are still experiencing this issue, please feel free to reopen it by creating a new issue and provide the following information, so that I may assist you:

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- On which platform does this occur? (iOS, Android, all, etc.)
- On which platform versions does this occur? (Android 4.2, iOS 7, all, etc.)
- Is this an issue with the Ionic Framework or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) that replicates the issue is extremely helpful.

If you wish to get help using Ionic, I recommended visiting [the forum](http://forum.ionicframework.com). There are many humans there who can offer sage advice.

Thank you for allowing me to assist you.

**Comment by Vinothapplife** [comment]
Same Error i am getting . and i am not able to build and deploy . please help this. Failed to load resource: the server responded with a status of 404 (Not Found) #117

**Comment by brandyscarney** [comment]
@Vinothapplife What steps did you take after cloning the project? Please see my previous comment: https://github.com/driftyco/ionic-conference-app/issues/117#issuecomment-167940165

**Comment by Vinothapplife** [comment]
![error](https://cloud.githubusercontent.com/assets/8506362/14720423/0474046a-081f-11e6-95af-fa162468789c.png)

@brandyscarney  after installed Cordova CLI: 6.1.1. i am getting this error. early waiting to see ionic 2 in my mobile. still i am not able to see. i hope you will give good solution. if yo have any demo please share to me. vinothapplife@gmail.com

**Comment by prakis** [comment]
Maybe this helps someone https://github.com/angular/angularfire2/issues/1271
