### ISSUE TITLE
Back button title not visible in FF

### ISSUE THREAD

**Issue by mpaland** [driftyco/ionic-conference-app#119]
I file this issue here, because it's observed in this app.
The word "Back" is not visible below the menu back arrow on a detail schedule page in FF43:
![capture](https://cloud.githubusercontent.com/assets/763140/12050737/c7ff1598-aef9-11e5-89cc-1ec56b366930.PNG)

**Comment by brandyscarney** [comment]
Thanks for the issue. This affects the starters & all Ionic 2 apps so I created an issue for it on the Ionic 2 repo: https://github.com/driftyco/ionic2/issues/831
