### ISSUE TITLE
"All" button not working in Schedule view

### ISSUE THREAD

**Issue by mpaland** [driftyco/ionic-conference-app#120]
Reproduce: Start app, in Schedule list, click on "Favorites". Try to click "All" then.
You can't switch back from "Favorites" to "All" in Schedule View.
Tested on FF43

**Comment by brandyscarney** [comment]
Thanks for the issue! There is an open issue for this on the Ionic2 repo since it affects segments in all Ionic2 apps: https://github.com/driftyco/ionic2/issues/819
