### ISSUE TITLE
Failed to load resource

### ISSUE THREAD

**Issue by mashaly100200** [driftyco/ionic-conference-app#123]
http://localhost:8101/build/css/app.ios.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8101/build/app.html Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8101/build/css/app.ios.css Failed to load resource: the server responded with a status of 404 (Not Found)

i have run npm install
and  also have installed ionic beta from more than two weeks

my ionic info is 
Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:
Ionic Version: 2.0.0-alpha.45
Ionic CLI Version: 2.0.0-beta.12
Ionic App Lib Version: 2.0.0-beta.6
OS:
Node Version: v5.0.0

 i use windows 10

**Comment by brandyscarney** [comment]
Can you update to the latest CLI beta (beta.15) `sudo npm install -g ioinc@beta` and see if that fixes it?

**Comment by ajaybeniwal** [comment]
yes i checked the latest update fixes it

**Comment by mashaly100200** [comment]
many thanks @brandyscarney  :+1:
