### ISSUE TITLE
EXCEPTION: No provider for ActionSheet!

### ISSUE THREAD

**Issue by thomastthai** [driftyco/ionic-conference-app#125]
C:\Users\Thomas\ionic2\ionic-conference-app>ionic info

Your system information:
After a fresh pull from repo, I noticed when clicking on the "Speakers" tab, an error was generated:

EXCEPTION: No provider for ActionSheet! (SpeakerListPage -> ActionSheet)

To fix the error, I made changes to file "speaker-list.js" as follows:

import {NavController, Page, ActionSheet} from 'ionic/ionic';
import {ConferenceData} from '../../providers/conference-data';
import {SpeakerDetailPage} from '../speaker-detail/speaker-detail';
import {SessionDetailPage} from '../session-detail/session-detail';

@Page({
  templateUrl: 'build/pages/speaker-list/speaker-list.html'
})
export class SpeakerListPage {
//  *** Modification ***
//  constructor(nav: NavController, confData: ConferenceData, actionSheet: ActionSheet) {
  constructor(nav: NavController, confData: ConferenceData) {
    this.nav = nav;
    this.confData = confData;
//  *** Modification ***
//   this.actionSheet = actionSheet;
    this.speakers = [];

    confData.getSpeakers().then(speakers => {
      this.speakers = speakers;
    });
  }

  goToSessionDetail(session) {
    this.nav.push(SessionDetailPage, session);
  }

  goToSpeakerDetail(speakerName) {
    this.nav.push(SpeakerDetailPage, speakerName);
  }

  goToSpeakerTwitter(speaker) {
    window.open(`https://twitter.com/${speaker.twitter}`);
  }

  openSpeakerShare(speaker) {
//  *** Modification ***
    ActionSheet.open( androidSheet || {
      buttons: [
        { text: 'Copy Link' },
        { text: 'Share via ...' },
      ],
      titleText: 'Share ' + speaker.name,
      cancelText: 'Cancel',
      cancel: () => {},
      buttonClicked: (index) => {
        switch (index){
          case 0 :
            // TODO
            return true;

          case 1 :
            // TODO
            return true;
        }
      }
    });
    
  }
}

---
Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:
Ionic Version: 2.0.0-alpha.47
Ionic CLI Version: 2.0.0-beta.15
Ionic App Lib Version: 2.0.0-beta.8
OS:
Node Version: v4.2.4

![image](https://cloud.githubusercontent.com/assets/16532581/12138703/a1fb09cc-b40f-11e5-97c5-a05ea277d3c5.png)

**Comment by brandyscarney** [comment]
Thanks for the issue! We refactored the ActionSheet in the latest release (alpha.47) and forgot to update it. It should be fixed now with my most recent commit. :smile: 

If you're interested we have a section on the refactor in the CHANGELOG: https://github.com/driftyco/ionic2/blob/master/CHANGELOG.md#200-alpha47-2016-1-4
