### ISSUE TITLE
Schedule page search input icon alignment

### ISSUE THREAD

**Issue by tlancina** [driftyco/ionic-conference-app#129]
![image](https://cloud.githubusercontent.com/assets/804331/12269390/c919d1ee-b916-11e5-820b-04e250627f21.png)

Only happens initially, focusing and blurring makes it to align correctly.

**Comment by mashaly100200** [comment]
yes  focusing and blurring makes it to align correctly but in ios only ,  in android not correct it

**Comment by tracktunes** [comment]
Ditto.  I noticed this same exact issue after running 'ionic serve' in the latest version of Firefox (43.0.4) running in Linux.

**Comment by matt4446** [comment]
The same thing occurs with the current alpha version as of Monday (I have not checked since) in my own prototypes. Unless both versions (scheduler and my own) have made the same mistakes (I've copied from the components documentation page) its probably a bug on the current version of the framework.

**Comment by brandyscarney** [comment]
This is filed here: https://github.com/driftyco/ionic2/issues/853

**Comment by tlancina** [comment]
Ah sorry, I'll close this then.
