### ISSUE TITLE
(change) event not working in NgFor

### ISSUE THREAD

**Issue by tarolechaitanya** [driftyco/ionic-conference-app#132]
I am populating select input type with ngFor.
But when I use (change) event, it throws an error stating "Error trying to diff"
If I don't use ngFor, (change) function is working on select  input type.

![ngforissue](https://cloud.githubusercontent.com/assets/14307698/12411854/d4bec0d6-bea7-11e5-8250-d6147d1b820a.png)

**Comment by brandyscarney** [comment]
Please submit an issue through our issue form and select `2.x` as the version of Ionic. This will place it in the [ionic](https://github.com/driftyco/ionic/issues?q=is%3Aopen+is%3Aissue+label%3Av2) repository with the proper labels.


Issue form: http://ionicframework.com/submit-issue/
