### ISSUE TITLE
Can't run app

### ISSUE THREAD

**Issue by bagusflyer** [driftyco/ionic-conference-app#135]
Got the following error message:

>  EXCEPTION: Error during instantiation of ConferenceApp!.BrowserDomAdapter.logError @ app.bundle.js:31450
app.bundle.js:31450 ORIGINAL EXCEPTION: TypeError: Cannot read property 'user:login' of undefinedBrowserDomAdapter.logError @ app.bundle.js:31450

What could be wrong? Thanks.

**Comment by brandyscarney** [comment]
There's an issue with the Storage right now. We plan on releasing a fix for it today and updating the conference app accordingly. I just commented out the storage code so if you clone a fresh copy it should work now: https://github.com/driftyco/ionic-conference-app/commit/7465745f3f550200976e07cbaa11cdb9f3f0fca9

**Comment by brandyscarney** [comment]
Closing this as you should be able to run it now.
