### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by dylanvdmerwe** [driftyco/ionic-conference-app#136]
Is there a reason why this sample project has not been done in Typescript?

**Comment by brandyscarney** [comment]
There is a typescript branch, but we don't want to force typescript on our users: https://github.com/driftyco/ionic-conference-app/tree/typescript

**Comment by dylanvdmerwe** [comment]
Interesting. What does the Ionic team recommend? What is the preference internally especially with the migration from Ionic 1 to 2?

**Comment by matt4446** [comment]
Note: not from the Ionic team 

I would recommend playing with Ionic at the moment. Even Angular is still still evolving (beta 1 to beta 2 has broken some of my changes in a different project - not Ionic). Try both ways and see which one suits your needs the most. 

As a outsider I have found it easy enough to get Ionic 2 working in TypeScript in VS Code (Ionic CLI  provides a flag for creating a starter project in TypeScript as well). I also started with Ionic 1 in TypeScript and so its quite familiar. I can can copy and paste code (less so the templates) quite easily between ionic 1 and 2 and work with them in similar ways.

The problems (far less to do with TypeScript) where Angular2 and Ionic 2 are concerned that they are so new there are so few resources to help with any difficult challenges... this is where I find TypeScript fairly superior. Ignoring the obvious good points that TypeScript has I can have much more confidence that i'm guessing that i'm talking to everything more correctly (from Angular2, Ionic to different Angular2 projects included in the solution - when they are built in TypeScript at least). Far less time reading docs and more time building / testing.

**Comment by tlancina** [comment]
You can start a typescript version of the starters by adding the `--ts` flag to the `start` command: `ionic start myapp --v2 --ts`.

I'm not sure we have an official stance at this point, but I personally find the workflow with VSCode and TypeScript to be quite enjoyable (having code completion, jump to definition, etc.), but in some ways it is another thing to learn, so if you have enough on your plate with ES6, Angular2, Ionic2, webpack, etc. then maybe it's not worth the extra mental overhead.

If you have time I would recommend trying both out to see if you have a preference either way.  Going to close this, but feel free to comment if you have further questions.
