### ISSUE TITLE
Missing app.build.js

### ISSUE THREAD

**Issue by inceptiveDipak** [driftyco/ionic-conference-app#137]
After downloading the ionic-conference-app successfully, i configured it successfully on my windows machine. When i run it using ionic serve then console show me "build/app.build.js" missing. Please help me how to resolve it.
Thanks in advance

**Comment by tlancina** [comment]
Hey what is the output of `ionic info` and what are the steps to reproduce the issue? Thanks.

**Comment by inceptiveDipak** [comment]
Thank's for replay.
I got solution.
After clone successfully i run 
npm i 
ionic serve

**Comment by brandyscarney** [comment]
Glad you got it working!
