### ISSUE TITLE
In the Webstorm IDE，Warning: Unknown html tag ion-content

### ISSUE THREAD

**Issue by chenzhizhuan** [driftyco/ionic-conference-app#140]
Use ionic v1 is no problem，but ionic v2 is warning: Unknown html tag ion-content，Help me, pls. thanks.

**Comment by tlancina** [comment]
Hey, it's very hard for us to help you without more information.  Also this sounds like it is potentially a webstorm issue and not an ionic conference app one.  Could you tell us how to reproduce the issue please?

**Comment by chenzhizhuan** [comment]
Runtime environment info：
MacBook Air (13-inch, Mid 2013) OS version: 10.10.5 (14F1605)
Webstorm 11.0.3

Step 1：
Clone ionic-conference-app from the github repository by webstorm

Step 2：
Run npm install from the project root.

Step 3：
Open the project by webstorm

Step 4：
Change webstorm preferences: Languages & Frameworks -> JavaScript -> JavaScript language version: ECMAScript 6 -> OK

Step 5：
Open app/app.html, click <ion-content> webstorm warning: Unknown html tag ion-content.

**Comment by brandyscarney** [comment]
Hey @chenzhizhuan, thanks for the issue and sorry it took so long to get back to you! I've followed the steps you provided and I am not able to see any errors, it also shows `ion-content` as an option as soon as I start typing `ion-c`. Is this still an issue for you? Here's my IDE info:

```
WebStorm 2016.1.1
Build #WS-145.597, built on March 30, 2016
JRE: 1.8.0_40-release-b132 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```

and here is a screenshot of how it appears for me:

![screen shot 2016-04-05 at 6 56 32 pm](https://cloud.githubusercontent.com/assets/6577830/14300752/98cdf8ee-fb60-11e5-9e03-bab79cbce4e1.png)

Could you try updating your Webstorm IDE version and see if that fixes it? Sorry again that it took so long for me to test this out. Thanks again!

**Comment by brandyscarney** [comment]
Going to close this as I don't think it is an issue anymore. Please let me know if otherwise and I will reopen. Thanks!

**Comment by arlowhite** [comment]
WebStorm 2016.1.1 doesn't have any errors on <ion-content> or other tags for me. So I think users really need to be on the latest version of WebStorm. They've been doing a lot of improvement to Typescript support as well.

**Comment by snpori** [comment]
Hey. i'm using Intellij Ultimate 2016.2.2 with the latest Phonegapp/Cordova plugin. the project is recognized as phongapp application (I can see this by the debug options) but the ion-* html directives are not recognizes.
Any suggestions?

**Comment by jwiesmann** [comment]
Not sure why, but i had to add the node_modules to my project (Settings, Languages & Frameworks, JavaScript, Libraries).
It was working before and stopped out of sudden, not quite sure what caused it :)

<img width="840" alt="screen shot 2017-05-08 at 21 06 23" src="https://cloud.githubusercontent.com/assets/7863773/25820703/7c283f0e-3432-11e7-9394-fbc85deaf6c1.png">
