### ISSUE TITLE
In the Webstorm IDE，Loop index...

### ISSUE THREAD

**Issue by chenzhizhuan** [driftyco/ionic-conference-app#141]
Often loop index...，Cause the overall operating efficiency is slow.

**Comment by tlancina** [comment]
Hey, it's very hard for us to help you without more information. Also this sounds like it is potentially a webstorm issue and not an ionic conference app one. Could you tell us how to reproduce the issue please?

**Comment by chenzhizhuan** [comment]
Runtime environment info：
MacBook Air (13-inch, Mid 2013) OS version: 10.10.5 (14F1605)
Webstorm 11.0.3

Step 1：
Clone ionic-conference-app from the github repository by webstorm

Step 2：
Run npm install from the project root.

Step 3：
Open the project by webstorm

Step 4：
Change webstorm preferences: Languages & Frameworks -> JavaScript -> JavaScript language version: ECMAScript 6 -> OK

Step 5：
Open app/pages/about/about.html and app/pages/about/about.js and app/pages/about/about.scss，Coding for a period of time，webstorm slow problems first, webstorm loop index problems again.

**Comment by brandyscarney** [comment]
It looks like this was reported to webstorm here: https://youtrack.jetbrains.com/issue/WEB-20651

If this is a different issue, could you open a new issue on their issue tracker? https://youtrack.jetbrains.com/issues/WEB
