### ISSUE TITLE
How to develop Ionic v2 app without ionic CLI ?

### ISSUE THREAD

**Issue by DILEEP-YADAV** [driftyco/ionic-conference-app#146]
Hi! @adamdbradley 
How to develop Ionic v2 app without ionic CLI? I mean manually with Bracket. I tested ionic-conference-app with bracket, but I did not show any response with chrome. How add lib file of ionic v2.

**Comment by patrickdronk** [comment]
So what is your question? You need a server to host the angular. So you either do ionic serve, or you find another way to host the angular

**Comment by brandyscarney** [comment]
I am going to close this as it is not an issue with the conference app. Please ask questions related to Ionic on the forums: https://forum.ionicframework.com/

Our CLI is also open source so you can go through and see what we use to serve your app (or any other commands): https://github.com/driftyco/ionic-cli/tree/master/lib/ionic

**Comment by DILEEP-YADAV** [comment]
@brandyscarney  Ok! no problem I got it and working fine. if we will talking about related question, I am sorry @brandyscarney. I am new for entirety  ionic framework.

**Comment by brandyscarney** [comment]
It's fine! This repository is s sample app of using Ionic 2.0. If you have any issues with using Ionic you can report them here: http://ionicframework.com/submit-issue/

Questions on using the framework are good to ask on the forums though. Most of the time you'll find someone who has the same question or an answer! :smile:
