### ISSUE TITLE
Tabs messed up iOS 8.4 simulator

### ISSUE THREAD

**Issue by chenzhizhuan** [driftyco/ionic-conference-app#148]
Chrome & Android device work fine，But iOS  device browser access（Have been deployed to http://ming.1g9f.com） and app run.

The screenshot：Before the three is wrong；After the three is right.
![1](https://cloud.githubusercontent.com/assets/4384043/13032476/40cb80e8-d32f-11e5-8420-1ade648c327a.png)
![2](https://cloud.githubusercontent.com/assets/4384043/13032477/40cd9e6e-d32f-11e5-81d5-69a9420ca028.png)
![3](https://cloud.githubusercontent.com/assets/4384043/13032478/40deb226-d32f-11e5-9f72-cbb833dfd289.png)

![4](https://cloud.githubusercontent.com/assets/4384043/13032504/51da8342-d330-11e5-9ba2-6eb027faa2c5.png)
![5](https://cloud.githubusercontent.com/assets/4384043/13032505/51e2d39e-d330-11e5-816a-438da27857e7.png)
![6](https://cloud.githubusercontent.com/assets/4384043/13032506/520d9ae8-d330-11e5-850e-29f7e14a1263.png)

CengcengtekiMacBook-Air:Home cengceng$ ionic info
Your system information:
Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:  
Ionic Version: 2.0.0-alpha.57
Ionic CLI Version: 2.0.0-beta.17
Ionic App Lib Version: 2.0.0-beta.8
ios-deploy version: 1.8.3 
ios-sim version: 4.1.1 
OS: Mac OS X El Capitan
Node Version: v0.12.7
Xcode version: Xcode 6.4 Build version 6E35b

**Comment by brandyscarney** [comment]
I'm sorry but I don't understand the problem. Could you explain when the tabs don't look correct?

**Comment by chenzhizhuan** [comment]
I'm sorry, I mistakenly said.Should be run to the apple machine, black screen and numerous according to the problems.There is no problem, you visit http://ming.1g9f.com?

**Comment by brandyscarney** [comment]
I'm going to close this because it doesn't look like it's an issue with the conference app. Can you please create a separate issue on the ionic repo if you're still experiencing this problem? https://github.com/driftyco/ionic/issues

Thanks!
