### ISSUE TITLE
Missing map on 2nd time open map view

### ISSUE THREAD

**Issue by inceptiveDipak** [driftyco/ionic-conference-app#150]
Hello,
I am configured ionic-conference-app on my android device, It run well, When i navigate to map view 1st time the map open successfully, but 2nd time it will not show. Also after login move to map view it doesn't show me map.
Thanks for help

**Comment by gigocabrera** [comment]
I was able to replicate the same issue on iPhone 6 with iOs 9.2.1. The map is missing on 2nd time no matter if you try to open it from menu or tabs

**Comment by jboothe** [comment]
This can easily be replicated in Chrome or Safari in serve mode. 

But note: Using tabs at bottom to navigate to and from Map tab works as expected. Only when using the side-nav Map, does the map not appear on subsequent selections.

**Comment by brandyscarney** [comment]
I updated the side menu and I can no longer reproduce this (I previously could). Could you pull the latest from the conference app, run a fresh `npm install` and `ionic serve` and let me know if it still happens? Thanks!

**Comment by gigocabrera** [comment]
I just pulled latest from the typescript branch and ran `npm install` and `ionic serve` and I get the error below now. Steps to reproduce are tricky, I started going back and forth between the map page and other pages until this error popped up.

Here's my info
Your system information:

Cordova CLI: 5.4.1
Gulp version:  CLI version 3.8.11
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.6-201605132240
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
OS: Windows 10
Node Version: v5.10.1
Browser: Chrome

![missingmap_150](https://cloud.githubusercontent.com/assets/6364855/15268589/a28a7b80-19b2-11e6-9099-daf0fe06c225.png)

**Comment by brandyscarney** [comment]
If you're able to consistently reproduce it can you create a new issue with the error? I can't reproduce this so some exact steps would be great. :smile:

**Comment by pjhartin** [comment]
@gigocabrera I noticed that you have not entered any API keys. The way that page is currently coded, each time the page is loaded a new request is sent to the API. As far as I understand using no API key limits the number of calls/responses you can receive in a given time. So if you are panning back and forth between the screen this may explain why.  Try it with an API key

**Comment by gigocabrera** [comment]
@brandyscarney I pulled latest on a different PC and I was not able to reproduce it there. I will not create a new issue for now until I'm able to consistently reproduce it with exact steps. 

@pjhartin I wasn't aware you needed an API Key for the maps (sorry still a noob). Maybe @brandyscarney  can confirm if this may have something to do with it
