### ISSUE TITLE
ion-item with a floating ion-label breaks when adding an icon

### ISSUE THREAD

**Issue by gigocabrera** [driftyco/ionic-conference-app#155]
Not sure if this is an ionic 2 issue or ionic-conference-app issue

If I add a left/right icons to an ion-item everything works fine

```
<ion-item>
    <ion-icon name="leaf" item-left primary></ion-icon>
    <ion-input type="text" placeholder="First Name"></ion-input>
    <ion-icon name="arrow-forward" item-right primary></ion-icon>
</ion-item>
```

![floating_with_left_right_icons_03](https://cloud.githubusercontent.com/assets/6364855/13259959/91d900ec-da27-11e5-8df5-0deea1e8c599.png)

If I add a left/right icons to an ion-item with a floating label, it breaks

```
<ion-item>
  <ion-icon name="leaf" item-left primary></ion-icon>
  <ion-label floating primary>First Name</ion-label>
  <ion-input type="text"></ion-input>
  <ion-icon name="arrow-forward" item-right primary></ion-icon>
</ion-item>
```

![floating_with_left_right_icons_02](https://cloud.githubusercontent.com/assets/6364855/13260026/c1f48954-da27-11e5-9908-8d227c4e492d.png)

If this is by design, can you help me find a solution?

**Comment by brandyscarney** [comment]
Yes, this is an ionic issue. I got around it for demo purposes by using `absolute` positioning on the icons:

https://github.com/driftyco/ionic/blob/2.0/demos/label/main.html#L15-L20
https://github.com/driftyco/ionic/blob/2.0/demos/label/main.html#L58-L68

This issue will resolve it: https://github.com/driftyco/ionic/issues/5319

**Comment by gigocabrera** [comment]
Thank you @brandyscarney you're the best (from one Floridian to another)

**Comment by brandyscarney** [comment]
Haha thanks. :smile:

**Comment by wellington1993** [comment]
Thanks!

**Comment by Balaraju1** [comment]
ion-select and ion-datetime floating label not working in ionic 4 beta 2. 
```
<ion-item>
<ion-label position="floating">Label :</ion-label>
<ion-select>
<ion-option-select></ion-option-select>
<ion-option-select></ion-option-select>
<ion-option-select></ion-option-select>
</ion-select>
</ion-item>
<ion-item>
<ion-label position="floating">Label :</ion-label>
<ion-datetime></ion-datetime>
</ion-item>
```
