### ISSUE TITLE
Sticky Headers do not work in Chrome and Android

### ISSUE THREAD

**Issue by jboothe** [driftyco/ionic-conference-app#159]
Sticky Headers work in iOS emulator and Safari browser but do not work in Android emulator or Chrome browser. 

Is this is by design?

**Comment by cyprusglobe** [comment]
@jboothe:Android doesn't support sticky headers

**Comment by madibalive** [comment]
is it configurable to force android to show it , am assuming it scss issue or is it platform hardware issue

**Comment by kuntal-b** [comment]
Facing same problem .
[Form Post](https://forum.ionicframework.com/t/problem-with-ionic-conference-app/46760)

**Comment by madibalive** [comment]
head it browser related  - appears chrome doesnt support these feature , so very unlikely to come in future release for android  -  best option is to for ionic 1.x sticky header

**Comment by brandyscarney** [comment]
This issue was moved to driftyco/ionic#5911
