### ISSUE TITLE
Typescript or ES Style this demo project?

### ISSUE THREAD

**Issue by ace-han** [driftyco/ionic-conference-app#160]
Hello, there

I'm new to ionic2. It's a little confusing to me that I'm wondering whether this demo project is written in `ES Javascript` or `Typescript` style

Since `ionic2` is built on `angular2` and `angular2` is based on `Typescript` .

If written in `ES`, shouldn't this project's scripts end with an extension `.ts` instead of `.js` to make the point clear that `ionic2` is encouraging/preferring `Typescript` over pure `ES`?

If written in `Typescript` why `loader` in `webpack.config.js` is `babel`? Is `babel` supports `Typescript` transpiling now?

Looking forward to your reply, thx in advance.

**Comment by ace-han** [comment]
Never mind, I figure it out. It's `ES6` style

However, I'm still wondering as a demo project. Why shouldn't it written in `Typescript` to align with the existing doc.

It's a little confusing...

**Comment by tlancina** [comment]
Great question.  We maintain two branches, `master` is JS and `typescript` is the TypeScript version: https://github.com/driftyco/ionic-conference-app/tree/typescript

I've updated the README to make this more clear: https://github.com/driftyco/ionic-conference-app/commit/4d7e0d74486c08ec6f872a456f1a3e0d10853402.

Going to close this, but feel free to let us know if you have any other questions/concerns, thanks!
