### ISSUE TITLE
Blank screen when opening ionic conference app

### ISSUE THREAD

**Issue by Sagamang** [driftyco/ionic-conference-app#164]
I just downloaded the conference app and followed the steps thats are provided on:
http://ionicframework.com/docs/v2/

However, running ionic serve gives me a blank screen. 

Fyi; no errors or warnings were given in the command prompt. 

I hope that someone can help me out? 
Because I have been working on 1 for a while and want to checkout ionic 2 now but I can not get it working. 
Does anyone has a clue of what I am doing wrong? 

If you need some more information for me than just ask. I will reply quickly (on workingdays). 

Thanks in advance.

**Comment by brandyscarney** [comment]
Can you tell me what steps you took? You may have missed the step to run `npm install`:

https://github.com/driftyco/ionic-conference-app#getting-started

**Comment by Sagamang** [comment]
It is working now. 
I did not followed the steps correctly. 

Thanks for your response Brandy.
