### ISSUE TITLE
Screens missing "elastic" effect in iOS

### ISSUE THREAD

**Issue by gigocabrera** [driftyco/ionic-conference-app#169]
I installed the conference app in my iPhone 6 and the schedule page does have the "elastic" effect when you pull down on the screen and it slowly scrolls back to the top. The rest of the pages do not behave like that. Is this something I need to add to each page to achieve this effect? Or is this a bug?

Ionic 1 does have that on every screen out of the box. 

What am I missing?

**Comment by brandyscarney** [comment]
@gigocabrera So this is actually on purpose right now to only work with scrollable pages. There's an open issue here on whether or not to add it for all pages: https://github.com/driftyco/ionic/issues/5275

Please add any feedback you have to that issue. Thanks for bringing this up!! :smile:
