### ISSUE TITLE
how to use icon with filter at place of .dot class ?

### ISSUE THREAD

**Issue by DILEEP-YADAV** [driftyco/ionic-conference-app#171]
Hi ! I have one question regard of ionic-conference-app. I want to use icon with filter at place of .dot class ? But Icon should according  filter data. just like I put filter on angular than Icon should angular. 
How can I do ? please help.

**Comment by brandyscarney** [comment]
@DILEEP-YADAV I'm not sure what you're asking for. Could you provide me a code sample or image of what you'd like to achieve?

**Comment by DILEEP-YADAV** [comment]
![filter](https://cloud.githubusercontent.com/assets/8583769/14117863/4c4f1fa4-f604-11e5-9ed4-ab2db40f74ca.PNG)

talking about this code:  schedule-filter.html


<ion-toolbar>
  <ion-buttons start>
    <button (click)="dismiss()">Cancel</button>
  </ion-buttons>

  <ion-title>
    Filter Sessions
  </ion-title>

  <ion-buttons end>
    <button (click)="applyFilters()">Done</button>
  </ion-buttons>
</ion-toolbar>


<ion-content class="outer-content">

  <ion-list>
    <ion-list-header>Tracks</ion-list-header>

    <ion-item *ngFor="#track of tracks" [attr.track]="track.name | lowercase">
      
        <span item-left class="dot"></span>
        
      <ion-label>{{track.name}}</ion-label>
      <ion-toggle [(ngModel)]="track.isChecked" secondary></ion-toggle>
    </ion-item>

  </ion-list>

  <ion-list>
    <button ion-item (click)="resetFilters()" danger detail-none class="reset-filters">
      Reset All Filters
    </button>
  </ion-list>

</ion-content>

**Comment by DILEEP-YADAV** [comment]
@brandyscarney  How to use multiple icons using array with filter track.
I mean :    Angular                                    with Angular icon
                 Communication                        with Communication icon 
                 Design                                      with Design   icon
                   ect.......................................................................
But using Json data as array. according with track name.

**Comment by brandyscarney** [comment]
@DILEEP-YADAV Please ask questions related to the framework on the [forums](https://forum.ionicframework.com/c/ionic-2) as this is not an issue with the conference app itself. You can achieve what you want by using an `ion-icon` with `item-left` like so:

```
<ion-item *ngFor="#track of tracks" [attr.track]="track.name | lowercase">
  <ion-icon item-left [name]="track.icon"></ion-icon>
  <ion-label>{{track.name}}</ion-label>
  <ion-toggle [(ngModel)]="track.isChecked" secondary></ion-toggle>
</ion-item>
```

where `track.icon` is defined for each `track`. If you have any further questions please create a topic on the forums at the link I provided. Thanks! :smile:

**Comment by DILEEP-YADAV** [comment]
ok ! thanks
