### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by chalme** [driftyco/ionic-conference-app#177]
What's wrong?  
The connection to the server was unsuccessful. (file:///android_asset/www/index.html)
if you know, please tell me.  thanks.

**Comment by brandyscarney** [comment]
Thanks for the issue! I'm going to close this as it doesn't seem like it's an issue with the conference app itself. Please visit our [forum](https://forum.ionicframework.com/) or [slack channel](http://ionicworldwide.herokuapp.com/) for questions about the framework. :smile:

If this is an issue with the conference app, please create a new issue with answers to the pre-populated questions:

![screen shot 2016-04-05 at 5 57 09 pm](https://cloud.githubusercontent.com/assets/6577830/14299335/dcbb9524-fb57-11e5-8fb6-7d463dfce44a.png)

Thanks so much!

**Comment by Jie-OY** [comment]
In the index.html has:
![image](https://cloud.githubusercontent.com/assets/10665384/18090499/9f44d250-6ef7-11e6-9660-5df3578896f9.png)
(Google Service)But there has GFW in China,so definitely you can't load it .
So,the solution is :use tools like Lantern to cross the GFW.
