### ISSUE TITLE
Feature request: login with FB ?

### ISSUE THREAD

**Issue by zhouhao27** [driftyco/ionic-conference-app#179]
This is very nice app from where we can study ionic 2. Is it possible to add some features like **login with Facebook** ? Thanks.

**Comment by kodeine** [comment]
+1 for fb native login.

**Comment by davorpeic** [comment]
+1

**Comment by refaelgold** [comment]
+1

**Comment by harpreet2602** [comment]
any news with fb login ?

**Comment by davorpeic** [comment]
Well, I just implemented FB login using this plugin https://github.com/nraboy/ng2-cordova-oauth, maybe I can copy my logic as PR to Conference app, but not sure if Drifty wants to enforce using some specific method (as they are many) to give an example of this. 

I'll also maybe switch to other plugin to give option to do FB login using native app (if exist).
Maybe it would be best that DriftyCo gives their input on this.

dp

**Comment by matheo** [comment]
Agreed,
given the different ways to implement this according the needs, it's not good to include an approach here. There are blogs out there using the `ionic-native` plugin (http://ionicframework.com/docs/v2/native/facebook/) or using some OAuth implementation.

For a project on mine, I have a Django backend registering the user with its social authentication (I used the native plugin here) and I just use OAuth on others with less requirements.

So, any contribution in this regard should have its own repository IMHO.

**Comment by jgw96** [comment]
Hello everyone! We are not planning on adding facebook auth to the conf app at the moment. There are docs [here](https://ionicframework.com/docs/v2/native/facebook/) that should help in implementing this. We do plan on adding optional auth at some point with ionic cloud auth though (: Since were not planning on adding FB auth I am going to close this issue for now.
