### ISSUE TITLE
build folder is missing in project directory.

### ISSUE THREAD

**Issue by cvssandhu** [driftyco/ionic-conference-app#181]
build folder is missing in project directory which is required to run the project.

while trying to create ionic 2 project from Node js then also its not generating.

**Comment by brandyscarney** [comment]
Thanks for the issue! I'm going to close this as it doesn't seem like it's an issue with the conference app itself. Please visit our [forum](https://forum.ionicframework.com/) or [slack channel](http://ionicworldwide.herokuapp.com/) for questions about the framework. :smile:

If this is an issue with the conference app, please create a new issue with answers to the pre-populated questions:

![screen shot 2016-04-05 at 5 57 09 pm](https://cloud.githubusercontent.com/assets/6577830/14299335/dcbb9524-fb57-11e5-8fb6-7d463dfce44a.png)

Thanks so much!
