### ISSUE TITLE
Research how zone/angular polyfills should be added

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic-conference-app#186]
There have been some changes to how zone and angular-polyfills are added to projects. Research the correct way and update our starters appropriately. 

Related: #185

**Comment by adamdbradley** [comment]
And for the starters: https://github.com/driftyco/ionic2-app-base/blob/master/package.json

**Comment by tlancina** [comment]
Right now we use angular2-polyfills for zone.js and reflect-metadata, which I believe is what Angular recommends at the moment. We also include es6-shim for compatibility on platforms where Promises and Collections aren't natively supported, which might be overkill according to https://github.com/angular/angular/issues/7124.

https://github.com/angular/angular/blob/master/modules/angular2/docs/bundles/overview.md#tldr
https://github.com/angular/angular/blob/master/modules/angular2/docs/bundles/overview.md#polyfills-and-external-dependencies

Angular2-webpack-starter uses core-js: https://github.com/AngularClass/angular2-webpack-starter/blob/master/src/polyfills.ts
Somewhat related: https://github.com/angular/angular/issues/5755

**Comment by jgw96** [comment]
We could almost get away with not polyfilling promises: http://caniuse.com/#feat=promises

**Comment by keithdmoore** [comment]
So after npm install, this is expected ?
npm WARN angular2@2.0.0-beta.15 requires a peer of reflect-metadata@0.1.2 but none was installed.
npm WARN angular2@2.0.0-beta.15 requires a peer of zone.js@^0.6.10 but none was installed.

**Comment by jgw96** [comment]
@keithdmoore Hey! So yep this is expected for right now, i put up an issue explaining why you would get these warnings here: https://github.com/driftyco/ionic/issues/6311. Thanks for using ionic!
