### ISSUE TITLE
Vertical Letterboxing on iPhone 6s

### ISSUE THREAD

**Issue by marcus-robinson** [driftyco/ionic-conference-app#196]
#### Short description of the problem:
Black bars appear top and bottom when viewing the app on iPhone 6s

#### What behavior are you expecting?
The app should display full screen.

**Steps to reproduce:**
1. Download the conference app, npm install and then ionic serve
2. Copy the config.xml file into the www directory, then zip the directory and deploy to phonegap build. (Note, a small config.xml modification is required - see below [0])
3. Install the compiled IPA on iPhone 6s

[0] Update the first line of config.xml after pasting into the www directory to ensure it's compatible with phonegap build:
```
<widget id="io.ionic.starter" version="0.0.1" xmlns="http://www.w3.org/ns/widgets" xmlns:gap="http://phonegap.com/ns/1.0" versionCode="1">
```

**Other information:** 
Please see attached screenshot:
![vertical-letterboxing](https://cloud.githubusercontent.com/assets/16617883/15453715/2f65b090-2063-11e6-8527-14bbe50bf760.PNG)

**Which branch are you on?** 
master

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.7
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
OS:
Node Version: v4.4.3

**Comment by brandyscarney** [comment]
@marcus-robinson Does this only happen when you modify the config file or does it happen before, as well? Also, can you only reproduce it on an iphone 6s or can it be done on a simulator?

**Comment by marcus-robinson** [comment]
@brandyscarney I'm on Windows, so the only way I've ever been able to test on iPhone is to deploy to PhoneGap and run a build and then install the resulting IPA file (can't run the iPhone simulator on Windows). 

The change made to the config file is just the replacement of the Cordova (cdv) namespace with the PhoneGap nampespace (gap) so I don't think this would be the issue.

I am able to replicate this issue on other projects using 2.0.0-beta.7 (which were not showing the issue on 2.0.0-beta.6), so I imagine it's an issue with the framework itself, not the conference app.

**Comment by marcus-robinson** [comment]
@brandyscarney it looks like this issue is caused by Ionic framework not including the correct splash screen image sizes. See stackoverflow post:
http://stackoverflow.com/questions/32312906/ios9-app-has-black-bars-on-top-and-bottom

I'll see if I can work out a solution and then post to the Ionic issues register.

**Comment by marcus-robinson** [comment]
I've posted instructions here on how to properly use PhoneGap Build with the latest Ionic so as to avoid this issue: https://forum.ionicframework.com/t/building-ionic-2-beta-7-apps-with-phonegap-build/53253
