### ISSUE TITLE
Nothing is being rendered in chrome after getting a fresh clone of sources.

### ISSUE THREAD

**Issue by aslamj** [driftyco/ionic-conference-app#199]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
Blank screen in chrome browser

#### What behavior are you expecting?
The App running in chrome browser.

**Steps to reproduce:**
1. Clone the repo (master in my case).
2. npm install, ionic build, ionic serve -c -s
3. Chrome opens, but has a blank screen. There is a JS error:
ionic $ serve  /  (www\index.html)
serve  /cordova.js  (mocked)
serve  /build/js/es6-shim.min.js
serve  /build/js/zone.js
serve  /build/js/Reflect.js
serve  /build/js/app.bundle.js
0     127510   error    Uncaught ReferenceError: plugin is not defined, http://localhost:8101/build/js/app.bundle.js, Line: 73081
1     132633   warn     Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys
2     132635   warn     Google Maps API warning: SensorNotRequired https://developers.google.com/maps/documentation/javascript/error-messages#sensor-not-required

```
insert any relevant code between the above and below backticks
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Which branch are you on?** master or typescript

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

**Comment by brandyscarney** [comment]
Please run through the following steps:

1. Pull the latest code from the conference app
2. Remove node modules in the project folder: `rm -rf node_modules/`
3. Run `npm install`

There was an issue with `ionic-native` but it should be good now. Thanks!
