### ISSUE TITLE
Clickable items should be a <button>

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic-conference-app#20]
Instead of:

```
<ion-item href="#" detail-push (click)="openSpeakerDetail(speaker.name)">...</ion-item>
```

it should be:

```
<button ion-item (click)="openSpeakerDetail(speaker.name)">...</button>
```

Also, the right arrow will automatically get added, and the 300ms delay will correctly kick in. And for accessibility reasons (the screen readers and when keyboard tabbing through elements, it has no clue that this random element is clickable and does important stuff).

**Comment by brandyscarney** [comment]
This is dependent on the next release having this fix in it: driftyco/ionic2#513
