### ISSUE TITLE
Upgrade typings to 1.0

### ISSUE THREAD

**Issue by itrethan** [driftyco/ionic-conference-app#203]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
The typings.json is still using old syntax, please upgrade.

#### What behavior are you expecting?
New typings.json syntax.

**Which branch are you on?** master or typescript
typescript

**Comment by matheo** [comment]
Refs https://github.com/driftyco/ionic2-app-base/pull/38

**Comment by jgw96** [comment]
Hello! We are now using typings 1.0. Thanks for using Ionic!
