### ISSUE TITLE
[Enhancement] Display tutorial only on first app use

### ISSUE THREAD

**Issue by ZiFFeL1992** [driftyco/ionic-conference-app#204]
#### What behavior are you expecting?

Display the start tutorial just the first time an user uses the app.

**Comment by ashishtilara** [comment]
I've been following this thread https://forum.ionicframework.com/t/conditional-rootpage/44613

And I tried to add following in `app.ts`
 ```javascript
import {Storage, LocalStorage} from 'ionic-angular';
...
  rootPage: any = TutorialPage;
  storage = new Storage(LocalStorage);
...
    platform.ready().then(() => {
      that.storage.get("didTutorial") .then((value) => {
        if (value === "true") {
          that.rootPage = TabsPage;
        }
      });
    });
```

and following in tutorial.ts

```javascript
import {Storage, LocalStorage} from 'ionic-angular';
...
  showSkip = true;
  storage = new Storage(LocalStorage);
...
  startApp() {
    this.storage.set("didTutorial", true);
    this.nav.push(TabsPage);
  }
```

but it still loads tutorial page, before moving to tabs page 😢

**Comment by ZiFFeL1992** [comment]
Is LocalStorage faster than SqlStorage? I mean I manage to get it work with SqlStorage but that introduces some delays while opening the app...

**Comment by ashishtilara** [comment]
not sure, I just used localStorage because user-data provider uses it as well.

**Comment by ZiFFeL1992** [comment]
Any advice on this?

**Comment by Bloggerschmidt** [comment]
or adding `this.rootPage = TabsPage;` in `app.ts`

    this.userData.hasLoggedIn().then((hasLoggedIn) => {
      this.enableMenu(hasLoggedIn === 'true');
      this.rootPage = TabsPage; // <-- here we go
    });

**Comment by Bloggerschmidt** [comment]
or adding an if statement after calling to enableMenu (`app.ts` arround line 66)

    this.userData.hasLoggedIn().then((hasLoggedIn) => {
      this.enableMenu(hasLoggedIn === 'true');
      if (hasLoggedIn === 'true') {
        this.rootPage = TabsPage;
      }
    });

**Comment by Bloggerschmidt** [comment]
you can do it by adding 

    if (hasLoggedIn === 'true') {
      this.rootPage = TabsPage;
    }

to 

    this.userData.hasLoggedIn().then((hasLoggedIn) => {
      this.enableMenu(hasLoggedIn === 'true');
      // <-- here we go
    });

in `app.ts` around line 66. Unfortunately the method to `enableMenu` only works at the first time. So you should add the same method to the page you're loading after the tutorial.

**Comment by brandyscarney** [comment]
This has now been added as part of https://github.com/driftyco/ionic-conference-app/pull/307. Thanks!
