### ISSUE TITLE
I get a splash screen followed by an empty screen.

### ISSUE THREAD

**Issue by waelkdouh** [driftyco/ionic-conference-app#214]
The app never loads any tabs. Running on an Android Nexus 6p device.

**Comment by yipjunjie** [comment]
I get a splash screen followed by an empty screen. What can I to do?

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Have you ran npm install before trying to run the app? Also, do you get any issues in the console when trying to run the app?

**Comment by AntonKL** [comment]
+1 on my iPhone 6+. Same issue. Works in browser with ionic serve but not in iPhone with xcode build.

**Comment by Ionitron** [comment]
Greetings @waelkdouh!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment]
Greetings @waelkdouh!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment]
Greetings @waelkdouh!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment]
Greetings @waelkdouh!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment]
Greetings @waelkdouh!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment]
Greetings @waelkdouh!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by AntonKL** [comment]
I must say that @Ionitron is going a little hard on this one, I think my inbox clearly has understood that this issue is closed, haha!

**Comment by Ionitron** [comment]
Greetings @waelkdouh!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by Ionitron** [comment]
Greetings @waelkdouh!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.

**Comment by brandyscarney** [comment]
Sorry about that @AntonKL. :smile: Do you have the same issue running the app in an iOS simulator or only when running the app on your device?
