### ISSUE TITLE
Remove typings and use @types instead

### ISSUE THREAD

**Issue by itrethan** [driftyco/ionic-conference-app#215]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
typings is annoying, use @types instead, it's awesome.

#### What behavior are you expecting?
remove typings, compliant with npm

**Comment by matheo** [comment]
@types doesn't have repositories, is this serious?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a suggestion for our build process I would urge that you open an issue about this in the [ionic cli](https://github.com/driftyco/ionic-cli) repo. Thanks for using Ionic!

**Comment by matheo** [comment]
Its not clear and there's no website to check what's @types about :-?

**Comment by itrethan** [comment]
@matheo Here is the repo https://www.npmjs.com/~types

**Comment by matheo** [comment]
Any info about `cli` utils? how to use them?
What's the advantage of migrate @typings to @types?
