### ISSUE TITLE
How to Change Gradle Version?

### ISSUE THREAD

**Issue by shuimuqinghua** [driftyco/ionic-conference-app#216]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
i can't change the gradle version to 2.10-all

#### What behavior are you expecting?
i hope you can tell me, how to change it.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our forum (forum.ionicframework.com). Thanks for using Ionic!

**Comment by joshbabb** [comment]
Was there ever any response on this in the forum?

**Comment by joshbabb** [comment]
Encountering this issue again, heh.  Any word?
