### ISSUE TITLE
Error: Cannot find module compilation error when use the custom components

### ISSUE THREAD

**Issue by thangam105** [driftyco/ionic-conference-app#217]
Error: Cannot find module 'custom/buttoncComponent' from 'D:\Angular2\Temp\Example Project\app\pages\home'.

**Steps to reproduce:**
1. I have installed the Jquery and local customComponent.d.ts file by typings.  typings install dt~jquery --global --save and  typings install file:./customComponent.d.ts  --global --save.
2.  I have used the customModule in ionic pages on that time i am not get error in typescript.
import {Component} from '@angular/core';
import {NavController} from 'ionic-angular';
import {CUSTOM_COMPONENTS} from 'custom/buttoncComponent';

@Component({
  templateUrl: 'build/pages/home/home.html',
  directives :[CUSTOM_COMPONENTS]
})
export class HomePage {
  constructor(private navCtrl: NavController) {

  }
}
3. I got compilation error when run the ionic serve in commend line.

I am fresher to ionic 2 and i am not understand to where  i mistake in my project.
Could you please help me?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our forum (forum.ionicframework.com). Thanks for using Ionic!
