### ISSUE TITLE
Different Alert View between web and mobile version

### ISSUE THREAD

**Issue by wonk4rol** [driftyco/ionic-conference-app#218]
#### Short description of the problem:
Different view alert in between Web and mobile version

#### What behavior are you expecting?
Must same output

#### This my code
```
logOut() {
    let alert = Alert.create({
        title: 'Alert',
        subTitle: 'You want to logout',
        buttons: [{
            text: 'Ok',
            handler: () => {
                // 'this.nav.remove', removes the 'Alert' from the stack
                // and then 'this.nav.setRoot' to change the rootPage
                this.nav.remove().then(() => {
                    this.nav.setRoot(LoginPage, {}, {animate: true, direction: 'back'});
                });
            }
        }]
    });
    this.nav.present(alert);
}
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
i have posted in 

> https://forum.ionicframework.com/t/alert-confirm-loading-etc-is-dark-overlap-by-overlay/58703/6

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Your system information:

Cordova CLI: 6.3.0
Gulp version:  CLI version 1.2.1
Gulp local:  
Ionic CLI Version: 2.0.0-beta.33
Ionic App Lib Version: 2.0.0-beta.19
OS: Distributor ID:	LinuxMint Description:	Linux Mint 17.2 Rafaela 
Node Version: v5.10.1

**Comment by jgw96** [comment]
Hello! Since it looks like this issue was already resolved in the forums I will be closing this issue. Thanks for using Ionic!
