### ISSUE TITLE
Laggy performance on app

### ISSUE THREAD

**Issue by kingkarki** [driftyco/ionic-conference-app#220]
It works fine on browser and ios simulator but not good in real ios devices. I tested with iphone 4s. There is long click dealy and scroll delay. This is the same issue from ionic 1.

**Comment by jgw96** [comment]
Hello @kingkarki ! Is this still an issue with the latest version of the conference app?

**Comment by jgw96** [comment]
Hello! I am going to close this one for now. We have made alot of improvements in our performance since August including AoT compile and more.

**Comment by kingkarki** [comment]
@jgw96  yes it looks good to me on iphone 6. Just curious to know is Routing back to ionic 2?
