### ISSUE TITLE
LoginPage & SignupPage Error with beta11

### ISSUE THREAD

**Issue by SoaringTiger** [driftyco/ionic-conference-app#222]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
When click menu->login , error shows:
EXCEPTION: Error: Uncaught (in promise): Template parse errors:

#### What behavior are you expecting?

**Steps to reproduce:**
1. Download ionic-conference-app source code
2. npm install
3. ionic serve

#Error with LoginPage
```
EXCEPTION: Error: Uncaught (in promise): Template parse errors:
There is no directive with "exportAs" set to "ngForm" ("ername</ion-label>
        <ion-input [(ngModel)]="login.username" ngControl="username" type="text" [ERROR ->]#username="ngForm" spellcheck="false" autocapitalize="off" required>
        </ion-input>
      </ion"): LoginPage@19:81
There is no directive with "exportAs" set to "ngForm" ("rd</ion-label>
        <ion-input [(ngModel)]="login.password" ngControl="password" type="password" [ERROR ->]#password="ngForm" required>
        </ion-input>
      </ion-item>
"): LoginPage@28:85
```

#Error with SignupPage
```
EXCEPTION: Error: Uncaught (in promise): Template parse errors:
There is no directive with "exportAs" set to "ngForm" ("rname</ion-label>
        <ion-input [(ngModel)]="signup.username" ngControl="username" type="text" [ERROR ->]#username="ngForm" required>
        </ion-input>
      </ion-item>
"): SignupPage@19:82
There is no directive with "exportAs" set to "ngForm" ("d</ion-label>
        <ion-input [(ngModel)]="signup.password" ngControl="password" type="password" [ERROR ->]#password="ngForm" required>
        </ion-input>
      </ion-item>
"): SignupPage@28:86
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:  
Ionic CLI Version: 2.0.0-beta.35
Ionic App Lib Version: 2.0.0-beta.19
ios-deploy version: 1.8.2 
ios-sim version: 4.1.1 
OS: Mac OS X El Capitan
Node Version: v4.2.4
Xcode version: Xcode 6.2 Build version 6C131e

**Comment by linvi** [comment]
Have you been able to fix this?

**Comment by JoeKool** [comment]
Issues due to angular RC3 to RC4

This worked for me:
http://stackoverflow.com/a/38648703

**Comment by brandyscarney** [comment]
Fixed by https://github.com/driftyco/ionic-conference-app/pull/224. Thanks!
