### ISSUE TITLE
Unable to click "Skip" on the tutorial page on Android 4.4.4

### ISSUE THREAD

**Issue by bushev** [driftyco/ionic-conference-app#223]
#### Short description of the problem:

Unable to click "Skip" on the tutorial page - session filter appeared.
#### What behavior are you expecting?

Tutorial will be closed

**Steps to reproduce:**
1. Use Android 4.4.4 (Samsung Galaxy S5) on Genymotion
2. Deploy application
3. Try click to "Skip"

**Run `ionic info` from terminal/cmd prompt:**
Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v5.11.1
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by phodal** [comment]
I have a similar issue with "SKIP" on the tutorial page. Sometimes, I click "SKIP" but not thing happen - keep in tutorial page, sometimes it can skip.

Devices: Android 5.1 (Meizu MX5)

Does it need more time to load tabs page?

**Comment by brandyscarney** [comment]
I was able to reproduce this using a Nexus 4 running `4.4.4` and a Nexus 5 running `5.1.0`. We're changing the structure of apps and making huge upgrades to the way templates are loaded so we're going to hold off on looking into this until those changes make it into master. Thanks!

**Comment by jgw96** [comment]
@bushev can you still reproduce this issue with the latest version of the conference app? Thanks!

**Comment by storyge** [comment]
+1,android 4.3 with crosswalk

**Comment by jgw96** [comment]
Hello! @storyge ! Is this still an issue with the latest version of the conference app? Thanks!

**Comment by jgw96** [comment]
Hello all! I am going to close this issue for now as we have made alot of changes (AoT for the most part) that fixes this issue. Thanks!
