### ISSUE TITLE
window.open not working on iOS

### ISSUE THREAD

**Issue by wberger** [driftyco/ionic-conference-app#225]
#### Short description of the problem:
When clicking on the "Tweet" button in the speakers list on iOS, nothing happens. `window.open` in `goToSpeakerTwitter` in `speaker-list.ts` does nothing.

#### What behavior are you expecting?
The page opens in an external browser.

**Steps to reproduce:**
1. Open the "Speakers" page.
2. Click on "Tweet" of speaker "Burt Bear"

```
goToSpeakerTwitter(speaker) {
    window.open(`https://twitter.com/${speaker.twitter}`);
}
```

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.3.0
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.36
Ionic App Lib Version: 2.0.0-beta.19
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v5.8.0
Xcode version: Xcode 7.3 Build version 7D175

**Comment by brandyscarney** [comment]
Added the InAppBrowser plugin which now opens the link externally in iOS. Please let me know if this still isn't working for you with the latest code, thanks!
