### ISSUE TITLE
Doesn't start! 

### ISSUE THREAD

**Issue by Stono** [driftyco/ionic-conference-app#227]
#### Short description of the problem:
Fresh clone of the app and I can't seem to get it to work.  Chrome opens and I see the three windows but they're just white and there is an error in the console

#### What behavior are you expecting?
It to work.

**Steps to reproduce:**
1.  git clone
2.  npm install
3.  ionic serve --lab

Gets the following console errors and the app is just white:
```
reflective_injector.js:689Uncaught No provider for Token Platform Pipes! (CompilerConfig -> Token Platform Pipes)
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
$ ionic info

Your system information:

Cordova CLI: 6.3.0
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.36
Ionic App Lib Version: 2.0.0-beta.19
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v6.2.2
Xcode version: Not installed

**Comment by ryantse** [comment]
I believe this is definitely related to the release of angular 2.0.0-rc.5 which occurred today. The application hasn't been updated to support the changes made in rc.5 which is causing the error.

**Comment by Stono** [comment]
Yeah; I was thinking the same after some googling... I'll try locking the dependencies and reporting back...

**Comment by Stono** [comment]
Sorted it, stuck in a pull request to lock it for the time being as I don't have the skills to fix this yet (just embarked on learning angular.js today :-))
