### ISSUE TITLE
cannot find module 'clone'

### ISSUE THREAD

**Issue by lwz7512** [driftyco/ionic-conference-app#233]
after I enter : ionic serve

report error:

Uh oh! Looks like you're missing a module in your gulpfile:
Cannot find module 'clone'

why?

**Comment by brandyscarney** [comment]
Could you run `ionic info` please from within your project folder and paste that info here? Thanks!

**Comment by lwz7512** [comment]
Your system information:

Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.30
Ionic App Lib Version: 2.0.0-beta.16
ios-deploy version: 1.8.6
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v4.4.0
Xcode version: Xcode 7.3 Build version 7D175

**Comment by lwz7512** [comment]
I cloned the ionic-conference-app repository, and npm install, then run : ionic serve
but report that error...

**Comment by brandyscarney** [comment]
Hmm could you try installing v2.0 of the CLI:

```
npm install -g ionic
```

Running `ionic -v` should give you:
```
$ ionic -v
2.0.0
```

**Comment by lwz7512** [comment]
reinstalled the cli, but the error remaining...
```
[liwenzhi@~/mobile/ionic-conference-app] $ ionic -v
2.0.0

[liwenzhi@~/mobile/ionic-conference-app] $ ionic serve
Uh oh! Looks like you're missing a module in your gulpfile:
Cannot find module 'clone'

Do you need to run `npm install`?
```

**Comment by jgw96** [comment]
@lwz7512 Hello! Would you mind updating to node 5 or node 6? Most likely this issue comes from you using npm 2. Thanks!

**Comment by lwz7512** [comment]
@jgw96 yes! you solved my problem! it works....

first, i reinstall npm to version 3.10.6;
then, rerun npm install to refresh the dependency tree;
last , ionic serve

done! thank you very much!

**Comment by jgw96** [comment]
No problem @lwz7512 ! Glad i could help!
