### ISSUE TITLE
Unable to build the project

### ISSUE THREAD

**Issue by napcat** [driftyco/ionic-conference-app#238]
#### Short description of the problem:
Unable to build the project.

#### What behavior are you expecting?
Install all the node modules and run ionic serve with success.

**Steps to reproduce:**
1 - Download Zip file from Github.

2 - Extract Zip to a dir

3 - Run npm install in dir extract location

4 - Run ionic serve

```
[11:05:37] Finished 'sass' after 1.22 s
Caught exception:
 Error: ENOENT: no such file or directory, lstat 'c:\Users\hsantos\Desktop\ionic-conference-app-master\typings\index.d.ts'
    at Error (native)
    at Object.fs.lstatSync (fs.js:887:18)
    at Object.realpathSync (fs.js:1518:21)
    at c:\Users\hsantos\Desktop\ionic-conference-app-master\node_modules\tsify\index.js:58:38
    at Array.map (native)
    at DestroyableTransform.flush [as _flush] (c:\Users\hsantos\Desktop\ionic-conference-app-master\node_modules\tsify\index.js:58:6)
    at DestroyableTransform.<anonymous> (c:\Users\hsantos\Desktop\ionic-conference-app-master\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:115:49)
    at DestroyableTransform.g (events.js:273:16)
    at emitNone (events.js:80:13)
    at DestroyableTransform.emit (events.js:179:7)
```

5 - Run another time npm install

```
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
```

**Ionic Info**
Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.37
Ionic App Lib Version: 2.0.0-beta.20
OS:
Node Version: v5.11.1

Windows 10

**Comment by brandyscarney** [comment]
Can you try updating the CLI to 2.0 to see if that fixes it?

```
npm install -g ionic
```

**Comment by napcat** [comment]
Hello,

I did an npm uninstall -g ionic and then a npm install -g ionic, and the problem still happens.

**Comment by brandyscarney** [comment]
What is your npm version? `npm -v`

**Comment by ittasks** [comment]
same exact problem , other projects compile fine.
```
> Win10
> Cordova CLI: 6.3.0
> Ionic Framework Version: 2.0.0-beta.10
> Ionic CLI Version: 2.0.0-beta.35
> Ionic App Lib Version: 2.0.0-beta.19
> Node Version: v4.4.7
> 
```

downloaded zip (today)
runned npm install (got 2 warnings about deprecated stuff)
**trying ionic serve,** 
getting this error:

```

> npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
> npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
> 
> c:\mobile\ionic-conference-app-master>ionic serve
> 
> Running 'serve:before' gulp task before serve
> [11:34:40] Starting 'clean'...
> [11:34:40] Finished 'clean' after 34 ms
> [11:34:40] Starting 'watch'...
> [11:34:40] Starting 'sass'...
> [11:34:41] Starting 'html'...
> [11:34:41] Starting 'fonts'...
> [11:34:41] Starting 'scripts'...
> [11:34:41] Finished 'html' after 124 ms
> [11:34:41] Finished 'scripts' after 129 ms
> [11:34:41] Finished 'fonts' after 138 ms
> [11:34:42] Finished 'sass' after 1.42 s
> Caught exception:
>  Error: ENOENT: no such file or directory, lstat 'c:\mobile\ionic-conference-app-master\typings\index.d.ts'
>     at Error (native)
>     at Object.fs.lstatSync (fs.js:839:18)
>     at Object.realpathSync (fs.js:1439:21)
>     at c:\mobile\ionic-conference-app-master\node_modules\tsify\index.js:58:38
>     at Array.map (native)
>     at DestroyableTransform.flush [as _flush] (c:\mobile\ionic-conference-app-master\node_modules\tsify\index.js:58:6)
>     at DestroyableTransform.<anonymous> (c:\mobile\ionic-conference-app-master\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:115:49)
>     at DestroyableTransform.g (events.js:260:16)
>     at emitNone (events.js:67:13)
>     at DestroyableTransform.emit (events.js:166:7)
> 
> Mind letting us know? https://github.com/driftyco/ionic-cli/issues


```

**Comment by karelbecerra** [comment]
Same issue (cloned today)

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.37
Ionic App Lib Version: 2.0.0-beta.20
ios-deploy version: Not installed
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v6.5.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by karelbecerra** [comment]
A simple workaround (copy/move main.d.ts file):

'cp typings/main.d.ts typings/index.d.ts'

**Comment by bishoymelek** [comment]
I have the same issue and don't know how to fix it :( please help ! I can pay money to make it work!

**Comment by karelbecerra** [comment]
bishoymelek you can move forward with the posted workaround (copy the file main.d.ts with the name index.d.ts) and it will work!

**Comment by ittasks** [comment]
> 'cp typings/main.d.ts typings/index.d.ts'

Thank you karelbecerra, your workaround works.

**Comment by napcat** [comment]
Thank you @karelbecerra for the workaround. ;)

**Comment by bishoymelek** [comment]
Thank you so much for your help!!

**Comment by mmazloum** [comment]
@ittasks & @napcat also fixed running "typings install" command

But then I get many errors telling "Cannot find promise" : 
TypeScript error: /Users/marwanmazloum/Desktop/Developpement/Sandbox/ionic-conference-app/node_modules/ionic-native/dist/plugins/sms.d.ts(40,89): Error TS2304: Cannot find name 'Promise'.
TypeScript error: /Users/marwanmazloum/Desktop/Developpement/Sandbox/ionic-conference-app/node_modules/ionic-native/dist/plugins/socialsharing.d.ts(32,95): Error TS2304: Cannot find name 'Promise'.
TypeScript error: /Users/marwanmazloum/Desktop/Developpement/Sandbox/ionic-conference-app/node_modules/ionic-native/dist/plugins/socialsharing.d.ts(43,9): Error TS2304: Cannot find name 'Promise'.

Besides when I run ionic serve I get a 404 on app.bundle.js any idea ?

**Comment by napcat** [comment]
@mmazloum I forgot to mention, but I also trying to fix it running the: 

`typings install`

I faced the same errors your are reporting.

**Comment by brandyscarney** [comment]
This is now fixed by https://github.com/driftyco/ionic-conference-app/pull/242. Please let me know if you're still running into this issue. Thanks!
