### ISSUE TITLE
Add a virtualScroll example.

### ISSUE THREAD

**Issue by masimplo** [driftyco/ionic-conference-app#240]
VirtualScroll is very important performance wise when you have lots of data. I would love to see a complete example of virtual scroll working with large lists and custom components.

**Comment by jgw96** [comment]
Will be fixed by this PR https://github.com/driftyco/ionic-conference-app/pull/386

**Comment by brandyscarney** [comment]
This has been added, thanks @jgw96! :fire: :bread:
