### ISSUE TITLE
Ahead of Time compilation - should I make all class members public

### ISSUE THREAD

**Issue by aggarwalankush** [driftyco/ionic-conference-app#248]
Hi All,

Can you please explain this commit [refactor(app): update to use public and same variables as starters](https://github.com/driftyco/ionic-conference-app/commit/79a69491041d911b5c625b5eeb7b97b42bff7dc5)

- Should I make all constructor parameters public? If yes, why platform and confData is not public in app.ts?
```
  constructor(
    public events: Events,
    public userData: UserData,
    public menu: MenuController,
    platform: Platform,
    confData: ConferenceData
  ) {
```
- Above commit also uses same variable name. Is it for AoT or just betting coding practice? 
- Should I also make class members(properties and methods) public?

Also, any link explaining how using public helps AoT will be really useful. I tried searching angular docs and stackoverflow but no luck.

Thanks

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com). Thanks for using Ionic!
