### ISSUE TITLE
ionic conference app got blank screen in iOS 10

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-conference-app#251]
_From @frankpolkm on September 22, 2016 3:54_

Hi, the ionic conference app doesn't work in iOS 10, blank after splash screen. 9.3 is OK.

_Copied from original issue: driftyco/ionic#8163_

**Comment by jgw96** [comment]
_From @rcjsuen on September 22, 2016 4:6_

Looks okay to me on my iOS 10.0.1 on my iPhone 6. How are you opening the application? I'm using Ionic View.

**Comment by jgw96** [comment]
_From @frankpolkm on September 22, 2016 13:12_

I just installed the latest version of Xcode, then using the command $ionic emulate, which pick up the default simulator setting: iPhone SE + iOS 10.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages?]. Thanks for using Ionic!

**Comment by finalxcode** [comment]
+1
