### ISSUE TITLE
README "Getting started" gives wrong instructions

### ISSUE THREAD

**Issue by astec** [driftyco/ionic-conference-app#255]
#### Short description of the problem:

Readme file recommend to install beta
> Install the ionic CLI (npm install -g ionic@beta)

#### What behavior are you expecting?

I expect it to recommend to install RC0

**Steps to reproduce:**
1. https://github.com/driftyco/ionic-conference-app
2. Search for `@beta`

**Comment by brandyscarney** [comment]
Nice catch. Fixed :wink:
