### ISSUE TITLE
integration with ionic Auth, Analytics, Deploy and Push

### ISSUE THREAD

**Issue by ashishtilara** [driftyco/ionic-conference-app#258]
Hi,

I just wanted to confirm if there are any plans to adding examples of Auth, Analytics, Deploy and Push in this project? 

cheers and Thank you for creating this awesome project, great resource to learn from.

**Comment by brandyscarney** [comment]
Thanks for the issue. :) We've decided that we aren't going to add these services to this app at this time. The conference app has really been our way of showing off the different framework components in a "real world" app and testing how they interact. We don't want to overload this app with too much going on. We do plan on creating an Ionic 2 app in the future that showcases these services, and will revisit adding them here at a later time.
