### ISSUE TITLE
building with latest RC, main.css doesn't seem to be generated 

### ISSUE THREAD

**Issue by RfanKD** [driftyco/ionic-conference-app#260]
Hi,

Thank you Ionic Team for the latest release candidate
but I seem to have a problem with I try to build with the sidemenu template

#### Short description of the problem:
building sidemenu project with latest RC and npm.
on first time starting the project up, the icons don't appear
when starting the project with ionic serve --lab, for a second, it seems the main.css has been removed from build folder. (In fact, the only file left in the build folder is polyfills.js)

**Steps to reproduce:**
1. ionic start --v2 myApp sidemenu
2. cd myApp
3. ionic serve --lab,(notice the icons don't appear) quit
4. ionic serve --lab, (notice the page1 don't appear, view console log to find that main.css seems to be deleted and not generated even when building is complete )

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-app-scripts#82

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Since this is a build issue and not an issue with the conference app I have moved this issue to the app-scripts repo. Thanks!
