### ISSUE TITLE
ionic state restore failed for RC0

### ISSUE THREAD

**Issue by frankpolkm** [driftyco/ionic-conference-app#261]
Would you please have a look? It's clean check out.

$ ionic state restore
Attempting to restore your Ionic application from package.json

Restoring Platforms

cordova platform add ios
cordova platform add android

Restore platforms is complete

Restoring Plugins

cordova plugin add cordova-plugin-whitelist
Caught exception:
 undefined 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

**Comment by jgw96** [comment]
Hello @frankpolkm are you getting this issue with a fresh copy of the conference-app?

**Comment by frankpolkm** [comment]
latest code is working now.
