### ISSUE TITLE
ionViewLoaded() has been deprecated. Please rename to ionViewDidLoad()

### ISSUE THREAD

**Issue by alexbainbridge** [driftyco/ionic-conference-app#263]
#### Short description of the problem:

Console error stating old code used (pre RC0) 

On the maps page by the looks of it

#### What behavior are you expecting?

No error in console

**Comment by Aristona** [comment]
Opened PR: https://github.com/driftyco/ionic-conference-app/pull/272

**Comment by jgw96** [comment]
Thanks! As i have merged the above mentioned PR I will be closing this issue.
