### ISSUE TITLE
"ionic start projectName conference --v2" command giving Cordova error

### ISSUE THREAD

**Issue by xgibbousx** [driftyco/ionic-conference-app#269]
#### Short description of the problem:

Ran "ionic start projectName conference --v2" and got "Error: Command failed: cordova plugin add --save cordova-plugin-device..." error during the "Adding initial native plugins" routine.

I have updated Ionic and Cordova by clearing npm cache, uninstalling both, and reinstalling both.

#### What behavior are you expecting?

To not get any errors.

**Steps to reproduce:**

1. Run "ionic start projectName conference --v2"

Full error:

Adding initial native plugins
[=============================]  100%  0.0s
{ Error: Command failed: cordova plugin add --save cordova-plugin-device && cord
ova plugin add --save cordova-plugin-console && cordova plugin add --save cordov
a-plugin-whitelist && cordova plugin add --save cordova-plugin-splashscreen && c
ordova plugin add --save cordova-plugin-statusbar && cordova plugin add --save i
onic-plugin-keyboard
Error: Current working directory is not a Cordova-based project.

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'cordova plugin add --save cordova-plugin-device && cordova plugin add --
save cordova-plugin-console && cordova plugin add --save cordova-plugin-whitelis
t && cordova plugin add --save cordova-plugin-splashscreen && cordova plugin add
 --save cordova-plugin-statusbar && cordova plugin add --save ionic-plugin-keybo
ard' } 'Error: Current working directory is not a Cordova-based project.\r\n'

Unable to add plugins. Perhaps your version of Cordova is too old. Try updating
(npm install -g cordova), removing this project folder, and trying again: (CLI v
2.1.0)

**Run `ionic info` from terminal/cmd prompt:**

Your system information:

You have been opted out of telemetry. To change this, run: cordova telemetry on.

6.3.1

Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS: Windows 7 SP1
Node Version: v6.6.0

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-cli#1460

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Since this is an issue with the cli and not the conference app I have moved this issue to that repo. Thanks!
