### ISSUE TITLE
Fonts folder in assets not necessary

### ISSUE THREAD

**Issue by Chris1308** [driftyco/ionic-conference-app#277]
#### Short description of the problem:
The Fonts folder in src/assets is not necessary and there are errors: "Error: EPERM: operation not permitted" when ionic serve is started.

#### What behavior are you expecting?
The folder can be deleted because the fonts are copied from folder in node_modules, you can see in copy.config.js

**Steps to reproduce:**
1. Clone Conference App
2. Run npm install
3. Run ionic serve

**Comment by brandyscarney** [comment]
Thanks! Fixed.
