### ISSUE TITLE
Debug Typescript Problem 

### ISSUE THREAD

**Issue by mfalzetta** [driftyco/ionic-conference-app#280]
The debuger for typescript not works in Chrome. Shows only JavaScript raw code.

I read many forums end nothing. A lot of time lost end nothing.

Somebody can help me?

Thaks!

**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### What behavior are you expecting?

**Steps to reproduce:**
1.
2.
3.

```
insert any relevant code between the above and below backticks (```)
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

**Comment by jwelmac** [comment]
Here is the best tool I have found for debugging Angular2/Typescript --> [Augury](https://augury.angular.io/)

**Comment by mfalzetta** [comment]
Thank You @jwelmac 

My debug is very bad yet.

I don't have more time to spend with this. Now i use console.log to resolve but i'm very frustrated.

Regards.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! With the latest version of app-scripts (which you can get by running `npm install @ionic/app-scripts@latest --save-dev` ) we now generate source maps which solves the above issues.

**Comment by jwelmac** [comment]
Thanks Justin,
In the previous version the complete source map was not generated which
limited debugging using the Dev tools.
Glad that's fixed. Awesome job!
