### ISSUE TITLE
Scrollbar not visible on schedule page.

### ISSUE THREAD

**Issue by Nishchit14** [driftyco/ionic-conference-app#282]
I'm trying to show 1000 schedules in 
```
<ion-content>
  <ion-list>
	<ion-item-sliding *ngFor="let p of people">
	  <ion-item>
               .........Item list.............
          </ion-item>
       </ion-item-sliding>
  </ion-list>
</ion-content>
```

Here scrollbar doesn't show up. So i can't assume how much data i've scrolled up :(
Please help me to show scrollbar. I'm trying since last 3 days.

Ionic2 .0
Android 5.1.1

**Comment by Nishchit14** [comment]
Any hope. ? :(

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com). Thanks for using Ionic!
