### ISSUE TITLE
Can't build for android

### ISSUE THREAD

**Issue by CallisteHanriat** [driftyco/ionic-conference-app#283]
I'm trying to install the app on my Android device so I've cloned the git repository and typed following commands : 
`npm install` to install packages needed by the project
`ionic serve --lab` to generate `www` folder
`ionic platform add android` to add android platform
`ionic build android` to build the project.

But I've the following error associated to the latest command which is in my `npm-debut.log` file.

`0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\A644044\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@3.10.7
3 info using node@v4.5.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle ionic-conference-app@~prebuild: ionic-conference-app@
6 silly lifecycle ionic-conference-app@~prebuild: no script for prebuild, continuing
7 info lifecycle ionic-conference-app@~build: ionic-conference-app@
8 verbose lifecycle ionic-conference-app@~build: unsafe-perm in lifecycle true
9 verbose lifecycle ionic-conference-app@~build: PATH: C:\Users\A644044\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\A644044\Documents\ionicProj\ionic-conference-app\node_modules\.bin;C:\Users\A644044\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\A644044\bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Java\jdk1.8.0_102;C:\Users\A644044\AppData\Local\Android\Sdk\tools;C:\Users\A644044\AppData\Local\Android\Sdk\platform-tools;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\A644044\AppData\Roaming\npm;C:\Users\A644044\AppData\Local\atom\bin;C:\Program Files\nodejs\C;C:\Program Files\Git\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\Windows\System32;C:\Program Files\doxygen\bin;C:\Program Files\nodejs;C:\Program Files\Java\jdk1.7.0_79\bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Java\jdk1.8.0_102;C:\Users\A644044\AppData\Roaming\npm;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
10 verbose lifecycle ionic-conference-app@~build: CWD: C:\Users\A644044\Documents\ionicProj\ionic-conference-app
11 silly lifecycle ionic-conference-app@~build: Args: [ '/d /s /c', 'ionic-app-scripts build' ]
12 silly lifecycle ionic-conference-app@~build: Returned: code: 1  signal: null
13 info lifecycle ionic-conference-app@~build: Failed to exec build script
14 verbose stack Error: ionic-conference-app@ build: `ionic-app-scripts build`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\A644044\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\A644044\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:829:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid ionic-conference-app@
16 verbose cwd C:\Users\A644044\Documents\ionicProj\ionic-conference-app
17 error Windows_NT 6.1.7601
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\A644044\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
19 error node v4.5.0
20 error npm  v3.10.7
21 error code ELIFECYCLE
22 error ionic-conference-app@ build: `ionic-app-scripts build`
22 error Exit status 1
23 error Failed at the ionic-conference-app@ build script 'ionic-app-scripts build'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the ionic-conference-app package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     ionic-app-scripts build
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs ionic-conference-app
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls ionic-conference-app
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
`

Here is my `ionic info` : 
`Your system information:

Cordova CLI: 6.3.1
Gulp version:  CLI version 1.2.2
Gulp local:
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS: Windows 7 SP1
Node Version: v4.5.0
`

Any ideas ?

**Comment by novas1r1** [comment]
I have this setup and it works for android:

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:
Ionic Framework Version: 2.0.0-rc.0-201610101823
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS: Windows 7 SP1
Node Version: v5.10.1

Maybe try to update your node version?

**Comment by CallisteHanriat** [comment]
Okay maybe I have to install gulp :) I let you know if it works soon

**Comment by CallisteHanriat** [comment]
OKay i've installed gulp and update node version and now it works, but i've 4.6.0 for node ;-) 

thanks
