### ISSUE TITLE
Black screen after switching quickly between pages

### ISSUE THREAD

**Issue by marcoturi** [driftyco/ionic-conference-app#284]
#### Short description of the problem:
Black screen after switching quickly between master detail pages (speaker page/schedule page).

#### What behavior are you expecting?
Not getting a black view

**Steps to reproduce:**
1. ionic run ios --device
2. tap on Speakers
3. tap on the first item
4. go back
5. repeat 2,3,4 quickly many times (we got it after 4-5 times)

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 

Ios on device: 10.0.2, iphone 6s
OS: Mac OS X El Capitan
Node Version: v6.6.0
Xcode version: Xcode 8.0 Build version 8A218a

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! This issue is already known and has been fixed in rc1. To update just run `npm install`in your copy of the conference app. Thanks again!
