### ISSUE TITLE
Commit 28f27aa causes the www directory and it's contents to be tracked by git

### ISSUE THREAD

**Issue by Simpler1** [driftyco/ionic-conference-app#286]
#### Short description of the problem:
Since commit `28f27aa`, running `ionic serve` wipes out the `www/.gitignore` file and does not ignore the www directory.

#### What behavior are you expecting?
The contents of the www directory should not be tracked by git.
What is the reason to even track the www directory itself?

**Steps to reproduce:**
1. clone https://github.com/driftyco/ionic-conference-app
2. cd ionic-conference-app
3. npm install
4. ionic serve
5. git status

```
$ git status
On branch master
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        deleted:    www/.gitignore

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        www/assets/
        www/build/
        www/index.html

no changes added to commit (use "git add" and/or "git commit -a")
```

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
```
$ ionic info

Your system information:

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS: Windows 7 SP1
Node Version: v6.7.0
```

**Comment by brandyscarney** [comment]
It will be fixed when a new version of app-scripts is released, see: https://github.com/driftyco/ionic-app-scripts/issues/134

The `www` directory needs to be there in order for users to clone the conference app as a starter. Without it, cordova plugins fail to install and it errors.
