### ISSUE TITLE
Cant find the main.dev.ts build Error

### ISSUE THREAD

**Issue by napcat** [driftyco/ionic-conference-app#287]
#### Short description of the problem:
Can't build the project with the latest version.
An error happens when ionic serve is run:

"unable to find C:\ionic-conference-app-master\src\app\main.dev.ts"

#### What behavior are you expecting?

**Steps to reproduce:**
1. Download the latest build from repo
2. npm install
3. ionic serve

**Other information:**
During npm install I see some red warnings: 
@angular/common@2.1.0
├── UNMET PEER DEPENDENCY @angular/compiler@2.1.0
...
@angular/platform-browser-dynamic@2.1.0
├── UNMET PEER DEPENDENCY @angular/platform-server@2.1.0
...
localforage-cordovasqlitedriver@1.5.0
│ └── UNMET PEER DEPENDENCY rxjs@5.0.0-beta.12
...
moment@2.15.1
├─┬ UNMET PEER DEPENDENCY rxjs@5.0.0-rc.1

**Run `ionic info` from terminal/cmd prompt:**
Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.0
Gulp local:
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS:
Node Version: v5.11.1

**Comment by qmagpie** [comment]
+1
I'm having the same issue as well.

**Comment by Chris1308** [comment]
Try npm install @ionic/app-scripts@latest and then start again

**Comment by brandyscarney** [comment]
We made some updates to the dependencies recently, could you try cloning the app, removing the `node_modules` directory and then running `npm install` again? Thanks!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
