### ISSUE TITLE
Error: ENOENT: no such file or directory - index.html

### ISSUE THREAD

**Issue by stalinkay** [driftyco/ionic-conference-app#288]
#### Short description of the problem:
I can't get ionic to display the sample ionic-conference-app project.

I had forked a previous version which worked fine but the current iteration doesn't have the index.html and other files in the www directory. Am I missing something?

#### What behavior are you expecting?
I expect the welcome page to be displayed in the lab view.

**Steps to reproduce:**
1. clone repo
2. run `npm install`
3. run `ionic serve --lab`

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

Error: ENOENT: no such file or directory, open '/Volumes/Reanimation/Work/Ministry of Industrialization/2016101401_Invest_Namibia_Conference_App/www/index.html'

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Your system information:

Cordova CLI: 6.3.0
Gulp version:  CLI version 1.2.1
Gulp local:  
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0
ios-deploy version: Not installed
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v5.12.0
Xcode version: Xcode 8.0 Build version 8A218a 

******************************************************
 Dependency warning - for the CLI to run correctly,      
 it is highly recommended to install/upgrade the following:     

 Install ios-deploy to deploy iOS applications to devices.  `npm install -g ios-deploy` (may require sudo)

******************************************************

**Comment by brandyscarney** [comment]
Can you update to the latest version of the CLI by running

```
npm install -g ionic
```

and then try? Thanks!

**Comment by stalinkay** [comment]
@brandyscarney Thank you that worked.

**Comment by khakserahul** [comment]
@brandyscarney Thank you
