### ISSUE TITLE
Error: Could not resolve './app.module' from src\app\main.dev.ts

### ISSUE THREAD

**Issue by karlpatrickespiritu** [driftyco/ionic-conference-app#290]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/
#### Short description of the problem:

When running `ionic serve`, gives me this error:

UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Could not resolve './app.module' from C:\xampp\htdocs\ionic-conference-app\src\app\main.dev.ts
#### What behavior are you expecting?

**Steps to reproduce:**
1. clone repo
2. npm install
3. ionic serve

``````
insert any relevant code between the above and below backticks (```)
``````

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Your system information:

You have been opted out of telemetry. To change this, run: cordova telemetry on.
6.3.0

Gulp version:  CLI version 3.9.1
Gulp local:
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS:
Node Version: v6.6.0

**Comment by brandyscarney** [comment]
Are you still getting this error if you clone the latest version of the conference app and run `npm install`?

**Comment by karlpatrickespiritu** [comment]
re install again and it's working now. thanks!
