### ISSUE TITLE
Solution: more aesthetically pleasing speaker list 

### ISSUE THREAD

**Issue by thomastthai** [driftyco/ionic-conference-app#298]
I made some enhancements to speaker-list.html to make it more intuitive and reorganized the layout to be more intuitive. Changes made are:
- Clicking on the avatar image or the name will take you to the speaker detail page. Before you would have to click on "About Name" to get there.
- Changed the question mark icon to a chatboxes and moved it down to the card footer. 

![localhost-8100- iphone 6 plus 1](https://cloud.githubusercontent.com/assets/16532581/19759507/3a6e4f38-9be2-11e6-8822-4f8b27cbec9f.png)

speaker-list.html

```
<ion-header>
  <ion-navbar>
    <button ion-button menuToggle>
      <ion-icon name="menu"></ion-icon>
    </button>
    <ion-title>Speakers</ion-title>
  </ion-navbar>
</ion-header>

<ion-content class="outer-content speaker-list">
  <ion-card *ngFor="let speaker of speakers" class="speaker">

    <ion-card-header>
      <ion-item>
        <ion-avatar item-left>
          <img [src]="speaker.profilePic" (click)="goToSpeakerDetail(speaker)">
        </ion-avatar>
        <button ion-button clear  (click)="goToSpeakerDetail(speaker)">{{speaker.name}}</button>
      </ion-item>
    </ion-card-header>

    <ion-card-content class="outer-content">
      <ion-list>
        <button ion-item *ngFor="let session of speaker.sessions" (click)="goToSessionDetail(session)">
          <h3>{{session.name}}</h3>
        </button>
      </ion-list>
    </ion-card-content>

    <ion-row no-padding>
      <ion-col>
        <button ion-button clear small color="primary" icon-left (click)="goToSpeakerTwitter(speaker)">
          <ion-icon name="logo-twitter"></ion-icon>
          Tweet
        </button>
      </ion-col>
      <ion-col text-center>
        <button ion-button clear small color="primary" icon-left (click)="openSpeakerShare(speaker)">
          <ion-icon name='share-alt'></ion-icon>
         Share
        </button>
      </ion-col>
      <ion-col text-right>
        <button ion-button clear small color="primary" icon-left (click)="openContact(speaker)">
          <ion-icon name='chatboxes'></ion-icon>
          Contact
        </button>
      </ion-col>
    </ion-row>

  </ion-card>
</ion-content>
```

Hope you like it.

**Comment by brandyscarney** [comment]
Thanks! I like the contact button being moved. I'll have to ask @bensperry about changing the `about name` link to be clicking on the users avatar. I remember he wanted it separately for some reason. :) Would you like to submit a PR for the button being moved?

**Comment by thomastthai** [comment]
Sure I can send the PR. The about name button doesn't flow with the other
events above it. I didn't see it and kept touching the picture or nane to
get more detail. It was when I looked at the code that I found it.

**Comment by brandyscarney** [comment]
I understand. We used to have it like that, I can't remember why we changed it though. :) Maybe we could compromise and have both and then I can ask him about removing it later?

**Comment by thomastthai** [comment]
Both is good. If going that route, separating the visual flow away from the
listing of events would add more visual context. Putting it where that
question mark icon was would tie it together with the name vs events.

**Comment by johnking** [comment]
thanks @thomastthai, I had it a try and it works.

**Comment by thomastthai** [comment]
My pleasure.

**Comment by thomastthai** [comment]
I submitted a pull request #306.
