### ISSUE TITLE
WARN: No gulpfile found!

### ISSUE THREAD

**Issue by mvsiva4u** [driftyco/ionic-conference-app#299]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
When I run ionic serve
WARN: No gulpfile found!
If your app requires a build step, you may want to ensure it runs before serve.

#### What behavior are you expecting?

**Steps to reproduce:**
1.
2.
3.

```
insert any relevant code between the above and below backticks (```)
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

**Comment by brandyscarney** [comment]
Please install the latest version of the CLI before running the conference app:

```
npm install -g ionic
```

The CLI version installed should be `2.1.1`. You can check the version by running `ionic -v` from a terminal. If you are still seeing the wrong version, try uninstalling it before reinstalling it using `npm uninstall -g ionic`. Thanks! :)
