### ISSUE TITLE
Is ion-pane required here? Can you use nothing instead?

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic-conference-app#30]
https://github.com/driftyco/ionic-conference-app/blob/master/www/app/modals/filter-schedule-modal.html#L1

**Comment by brandyscarney** [comment]
Fixed in this issue: https://github.com/driftyco/ionic2/issues/321 but let's leave this open until we can implement this

**Comment by brandyscarney** [comment]
Fixed in #55
