### ISSUE TITLE
FORM_DIRECTIVES, FormBuilder,  ControlGroup, Validators, AbstractControl in ionic2

### ISSUE THREAD

**Issue by mvsiva4u** [driftyco/ionic-conference-app#300]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/
#### Short description of the problem:

How to use FORM_DIRECTIVES, FormBuilder,  ControlGroup, Validators, AbstractControl in ionic2
#### What behavior are you expecting?

**Steps to reproduce:**
1.
2.
3.

``````
insert any relevant code between the above and below backticks (```)
``````

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

**Comment by brandyscarney** [comment]
Thanks for the issue! Please visit our [forum](https://forum.ionicframework.com/) or [slack channel](http://ionicworldwide.herokuapp.com/) for questions about the framework. :smile:

**Comment by mvsiva4u** [comment]
Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
OS: Windows 7 SP1
Node Version: v6.5.0
