### ISSUE TITLE
Replace Segment with Tabs

### ISSUE THREAD

**Issue by thebasix** [driftyco/ionic-conference-app#301]
I want to replace Segment (All, Favorites) with Tabs. How would the code look like?

I'm asking because I've tried to replace with tabs but it didnt work.

Regards

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com). Thanks for using Ionic!

**Comment by thebasix** [comment]
The Ionic community sucks big time! No one ever responds!

**Comment by brandyscarney** [comment]
@thebasix The best way to get help is to post on the forums or in the [Ionic Worldwide Slack](http://ionicworldwide.herokuapp.com/) channel. It helps to be descriptive about what you are trying to accomplish including images of your desired result, what you have tried, code examples and/or a repository. @mhartington frequents the forum and the Ionic Worldwide Slack. I recommend the `#ionic-v2` channel for Ionic 2 questions. I'm not sure what your end goal is, but we don't recommend using tabs inside of content. The Ionic Tabs component should be used for navigation (it resembles Material Design bottom navigation: https://material.google.com/components/bottom-navigation.html) and the Ionic Segment should be used for changing between views (it resembles Material Design tabs: https://material.google.com/components/tabs.html).
