### ISSUE TITLE
conference-app not running in Edge [RC2]

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-conference-app#302]
_From @mpaland on November 4, 2016 14:26_

#### Short description of the problem:
I installed node, ionic, cordova and conference-app from scratch for testing RC2.
Started with: ionic serve
While Firefox 49 is running fine, MS Edge (on Win 10) isn't. Screen is blank.

#### What behavior are you expecting?
Running conference app in Edge.

#### Console error log
```
SCRIPT65535: Argument not optional
polyfills.js (3,16552)
SCRIPT5007: Unable to get property '__symbol__' of undefined or null reference
main.js (5640,1)
```

**Steps to reproduce:**
1. Latest ionic-conference-app, ionic2 RC2
2. ionic serve

**Which Ionic Version?** 2.x RC2

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Your system information:

Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.2
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
Ionic App Scripts Version: 0.0.39
OS:
Node Version: v6.9.1

_Copied from original issue: driftyco/ionic#9025_

**Comment by danbucholtz** [comment]
http://stackoverflow.com/questions/39540851/angular-2-not-working-with-ms-edge

**Comment by mpaland** [comment]
Thanx, Dan!
I updated to zone.js to 0.6.25 as recommended and rebuilt.
Unfortunately the error is still the same. I can't confirm the fix.
Tested on Windows 10 with actual Edge 14.14393

```
Your system information:

 ordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.2
Ionic CLI Version: 2.1.7
Ionic App Lib Version: 2.1.4
Ionic App Scripts Version: 0.0.43
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.1
Xcode version: Not installed
```

**Comment by danbucholtz** [comment]
Hi @mpaland,

Sorry, I wasn't proposing a fix, we were just talking about this internally and I posted the link as a reference. We'll get this fixed sooner-than-later. I am seeing it too on Edge.

Thanks,
Dan

**Comment by mpaland** [comment]
This works fine again with latest ionic nightly (upcoming RC4).
Issue can be closed. Thanks!

**Comment by manucorporat** [comment]
@mpaland glad to hear that!
