### ISSUE TITLE
How to build by enableprodmode() 

### ISSUE THREAD

**Issue by mvsiva4u** [driftyco/ionic-conference-app#308]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:

How to build by enableprodmode() 
#### What behavior are you expecting?

**Steps to reproduce:**
1.
2.
3.

```
insert any relevant code between the above and below backticks (```)
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

**Comment by brandyscarney** [comment]
Thanks for the issue! I'm going to close this as it doesn't seem like it's an issue with the conference app itself. Please visit our [forum](https://forum.ionicframework.com/) or [slack channel](http://ionicworldwide.herokuapp.com/) for questions about the framework. :smile:

If this is an issue with the conference app, please create a new issue with answers to the pre-populated questions:

![screen shot 2016-04-05 at 5 57 09 pm](https://cloud.githubusercontent.com/assets/6577830/14299335/dcbb9524-fb57-11e5-8fb6-7d463dfce44a.png)

Thanks so much!
