### ISSUE TITLE
Property 'query' does not exist on type 'Storage'.

### ISSUE THREAD

**Issue by mvsiva4u** [driftyco/ionic-conference-app#314]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short deiscription of the problem:
if i used below sqllite to get data from sql list database
this.storage.query(sql, [data.institutionid, data.app, data.capability]);

#### What behavior are you expecting?

**Steps to reproduce:**
1.
2.
3.

```
insert any relevant code between the above and below backticks (```)
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

**Comment by brandyscarney** [comment]
This issue was moved to driftyco/ionic-storage#45
