### ISSUE TITLE
Pipes in latest ionic2 version not working

### ISSUE THREAD

**Issue by mvsiva4u** [driftyco/ionic-conference-app#321]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
import {TranslateService, TranslatePipe, TranslateLoader, TranslateStaticLoader} from 'ng2-translate/ng2-translate';
pipes: [TranslatePipe],

Please suggest how to use pipes in the latest version of IONIC2 since i used like above in older verison it is working fine.

#### What behavior are you expecting?

**Steps to reproduce:**
1.
2.
3.

```
insert any relevant code between the above and below backticks (```)
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! You should be importing the `TranslatePipe` in your [app module](https://github.com/driftyco/ionic2-starter-tabs/blob/master/src/app/app.module.ts) and putting it in the providers array there. You can see our docs on how to use ng2-translate [here](http://ionicframework.com/docs/v2/resources/ng2-translate/).
