### ISSUE TITLE
custom filters in lastest ionic version 

### ISSUE THREAD

**Issue by mvsiva4u** [driftyco/ionic-conference-app#323]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Old version i used custom filters like below one. IN latest version it is not working as expected.
import {PricePipe} from '../../pipes/pipes';
pipes: [PricePipe]
**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by mvsiva4u** [comment]
import {Pipe} from '@angular/core';
// Tell Angular2 we're creating a Pipe with TypeScript decorators
@Pipe({
  name: 'PricePipe'
})
export class PricePipe {
  // Transform is the new "return function(value, args)" in Angular 1.x
  transform(value:number, args:string[]) : any {
	  return value.toFixed(2).replace(/(\d)(?=(\d{3})+\.)/g, '$1,');
    //return parseFloat(value).toFixed(2).toLocaleString();
  }
}

**Comment by jgw96** [comment]
Hello @mvsiva4u thanks for opening an issue with us! Are you still having this issue with the latest version of the conference app?

**Comment by mvsiva4u** [comment]
Yes , The moment i'm trying to use it like the above mentioned code it is throwing error.

**Comment by jgw96** [comment]
Hello @mvsiva4u , unfortunately I cannot reproduce this issue with the latest version of the conf app. Could you post a repo that i can use to reproduce your issue?

**Comment by brandyscarney** [comment]
Thanks for the issue. I'm not able to reproduce this in the conference app, and since this is custom code it's more of a support question. Please visit our [forum](https://forum.ionicframework.com/) or [slack channel](http://ionicworldwide.herokuapp.com/) for questions about the framework. :smile:
