### ISSUE TITLE
Doing a common mistake?

### ISSUE THREAD

**Issue by gotu** [driftyco/ionic-conference-app#324]
Is this demo app for ionic2 doing a common mistake?! Or am I missing/missunderstanding something?

see: https://ionicframework.com/docs/v2/faq/#common-mistakes

Common mistakes
Page components acting odd
Page components that are loaded with NavController do not need selectors added to them. If you place a selector on a page component, chances are it will animate incorrectly and have the wrong styles applied to it.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! So this is actually a case of the docs being wrong. Components should now have a selector on them as of RC0. I have opened a PR [here](https://github.com/driftyco/ionic-site/pull/904) to update the docs to reflect this change.
