### ISSUE TITLE
build folder files get deleted during ionic serve

### ISSUE THREAD

**Issue by MAEVE007** [driftyco/ionic-conference-app#326]
I get these error when i run my app. N these files main.css ,polyfills.css were deleted themselves. Please suggest something. 

<Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8100/build/main.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8100/build/polyfills.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://0.0.0.0:35729/livereload.js?snipver=1 Failed to load resource: net::ERR_ADDRESS_INVALID
http://localhost:8100/build/main.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8100/build/polyfills.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8100/build/main.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8100/build/main.css Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by brandyscarney** [comment]
This issue was moved to driftyco/ionic-app-scripts#617
