### ISSUE TITLE
Seems slower than Ionic 1

### ISSUE THREAD

**Issue by NgYueHong** [driftyco/ionic-conference-app#327]
I am trying out this app to see the component of Ionic 2 and how it perform. My biggest hope is to see it perform much faster than Ionic 1. The components are looking great. But it's performance seems to be much slower than Ionic 1. I am testing it on a low end Android 4.4 phone. The respond and everything is quite slow as compare to my app which is developed using Ionic 1.

Really hope the performance of Ionic 2 can be improved and perform better than Ionic 1.

**Comment by sunny061** [comment]
I ran the app on my phone (Samsung Galaxy A5 2014) using "ionic run android". The splashscreen shows for around 15-18 seconds. It is shockingly slow. Once the app is finished loading, the performance isn't great either. It takes about a second for the tab to change. Surely this is not normal. Can anyone else share their experience on loading times and performance of this app?

**Comment by brandyscarney** [comment]
@sunny061 Could you make sure you have the latest version of the project, a fresh copy of `node_modules`, and then try running `ionic run android --prod` and let me know what times you're seeing. Thanks!

**Comment by sunny061** [comment]
I tried "ionic run android --prod". The splash screen loading time has decreased to about 6.5 - 7 seconds. It's a big improvement from the 15-18 seconds I was getting without the "--prod" flag. Will this be improved some more?

**Comment by mohamedsharaf** [comment]
Are you performing any storage read before setting rootPage?

**Comment by sunny061** [comment]
@mohamedsharaf Don't think so. I am just running the app without any modifications and I haven't looked into the code so I don't know if the app does any storage read. Also, I am not running any other apps at the same time.

**Comment by jgw96** [comment]
@sunny061 would you mind posting the specs of your device?

**Comment by mohamedsharaf** [comment]
i have tested on samsung note 5 
it takes around 4 or 5  seconds till splash screen disappear 
is this normal for ionic2 or i have to work on improvement


note5
4GB RAM
Exynos 7420 Octa
http://www.gsmarena.com/samsung_galaxy_note5-7431.php
android 6

**Comment by jgw96** [comment]
Hello all, thanks for using Ionic! I am going to close and lock this thread for now as [this one was](https://github.com/driftyco/ionic/issues/6776#issuecomment-271903602). We are constantly working on improving performance with Ionic including load time performance so look for more improvements to come in the near future around performance.

**Comment by jgw96** [comment]
Also, just so everyone knows, you can find alot of good info on the issue i linked to above on some of our plans on how to improve load time performance.
