### ISSUE TITLE
Blank Screen After SplashScreen Loading on Visual Studio 2015

### ISSUE THREAD

**Issue by Pankul** [driftyco/ionic-conference-app#328]
The App is working fine when we run on Command Line.But when i run on **Visual studio** then it show me blank screen build folder not generated.Please guide me how to run this project in visual studio 2015

![pms1](https://cloud.githubusercontent.com/assets/8099692/21045404/346eafa4-be26-11e6-8363-93516218995b.png)

**Comment by jgw96** [comment]
Hey, thanks for opening an issue with us! Quick question, do you have the [VS TACO tools](https://taco.visualstudio.com/) installed?

**Comment by jgw96** [comment]
Hello @Pankul I am going to close this issue for now as it has been a while since there was any reply on this issue. If your still running into it please feel free to comment and i will reopen. Thanks!
