### ISSUE TITLE
IOS Emulator

### ISSUE THREAD

**Issue by saffalee23** [driftyco/ionic-conference-app#329]
I can't emulate in ios. The build breaks at the google maps sdk.

Ionic Conference/Plugins/cordova-plugin-googlemaps/GoogleMaps.h:10:9: fatal error: could not build module 'GoogleMaps'
#import <GoogleMaps/GoogleMaps.h>

**Steps to reproduce:**
ionic emulate ios

**Comment by brandyscarney** [comment]
If you are having problems running the conference app itself, please make sure you have done the following:

1. Install the latest version of the CLI (at the time of writing it is `2.1.18`)
 
    ```
    npm uninstall -g ionic
    npm install -g ionic
    ```

2. Pull the latest code for the conference app
3. Delete the `node_modules` folder and run `npm install`
4. Remove the `ios` platform and add it back:

    ```
    ionic platform remove ios
    ionic platform add ios
    ```

5. Clean the build by running `ionic-app-scripts clean`
6. Try running it again (adding the `--prod` flag will create a prod build)

    ```
    ionic emulate ios --prod
    ```

If you are still seeing issues after doing this, please create a new issue or update this issue to include the information in the issue template and I'll reopen it. Thanks!
