### ISSUE TITLE
Visual Studio IDE support

### ISSUE THREAD

**Issue by msatyan** [driftyco/ionic-conference-app#337]
Please enable Visual Studio IDE support for this magnificent sample project; a friendly yet powerful IDE...

**Comment by jgw96** [comment]
Hello @msatyan , could you post some more info about this issue? Ionic and Cordova apps are fully supported as long as you have the [VS Taco](https://www.visualstudio.com/vs/cordova/) tools installed.

**Comment by msatyan** [comment]
Thanks very much Justin, I will try it, 
You guys are doing great work, really appreciate.
For the time being we may close the issue then.
