### ISSUE TITLE
File structure of app are out of date

### ISSUE THREAD

**Issue by RobertoDebarba** [driftyco/ionic-conference-app#341]
**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request

**Current behavior:**
In the RC0 of Ionic was added two files: main.dev.ts and main.prod.ts, but recently the were removed on commit https://github.com/driftyco/ionic-conference-app/commit/723bf0f3a97d82e271fc27f0618ccd0be33b9109, but the file structure of app on README.MD was not updated. Who is right?

ionic-conference-app/
|-- src/
|    |-- app/
|    |    └── main.dev.ts
|    |    └── main.prod.ts

**Expected behavior:**
The file structure of app on README and commited file be the same.

**Comment by jgw96** [comment]
Thanks for opening an issue with us! Fixed this here https://github.com/driftyco/ionic-conference-app/commit/86f35fbc1863e2e1b52896b4918a34db8a0c779c.
