### ISSUE TITLE
slow launch time

### ISSUE THREAD

**Issue by philrob** [driftyco/ionic-conference-app#344]
At ionic (e.g. Dan) you state that improving the launch time of ionic2 is currently your #1 priority.
At the same time ionic have closed and locked issues dealing with this on the basis that 'you're working on it', which to some degree I can understand. Meanwhile, it would appear (from those closed issues) this is also a #1 priority with quite a number of developers who are evaluating hybrid frameworks to choose which one they go forward with. Could I suggest, therefore, that you provide some regular ongoing feedback, or updates specifically on this #1 priority. Maybe this could be added to the overall 'changelog' for new releases of ionic2?

Personally, because every environment is different, I'm using your ionic-conference-app to monitor the situation for my specific environment as it provides a standard 'benchmark' (including for best practices as its developed by yourselves). Currently I experience a launch time for the conference app of ~8 secs on my Nexus 7 (2013) running Android 6.0.1 (both rc4 and rc5), which I'm afraid, I feel is a little too long for me.

I REALLY like ionic for many other VERY important reasons (pedigree, support, documentation, facilities, ...). Also as an experienced developer, I do fully appreciate you have NOT yet reached your final release but, would really like more ongoing feedback on what to expect. Maybe, a specific section in the 'changelog' for each new release candidate?

**Comment by brandyscarney** [comment]
This issue was moved to driftyco/ionic-app-scripts#670
