### ISSUE TITLE
IONIC INSTALL ERROR - please HELP-ME

### ISSUE THREAD

**Issue by ptmagalhaes** [driftyco/ionic-conference-app#347]
**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

on install ionic i see error

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "cordova" "ionic"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! path /usr/local/lib/node_modules/ionic/node_modules/cordova-serve
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules/ionic/node_modules/cordova-serve'
npm ERR!     at Error (native)
npm ERR!  { Error: EACCES: permission denied, access '/usr/local/lib/node_modules/ionic/node_modules/cordova-serve'
npm ERR!     at Error (native)
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules/ionic/node_modules/cordova-serve' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/teste/Desktop/Ionic/sirona/npm-debug.log
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by brandyscarney** [comment]
Did you see my comment on the other issue you just created? This is not a bug with the conference app. Please refer to my previous comment: https://github.com/driftyco/ionic-conference-app/issues/346#issuecomment-273266837
