### ISSUE TITLE
HOW TO SET IMAGE FULLSCREEN IONIC 2

### ISSUE THREAD

**Issue by ptmagalhaes** [driftyco/ionic-conference-app#349]
**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by brandyscarney** [comment]
Thanks for the issue! I'm going to close this as it doesn't seem like it's an issue with the conference app itself. Please visit our [forum](https://forum.ionicframework.com/) or [slack channel](http://ionicworldwide.herokuapp.com/) for questions about the framework. :smile:

If this is an issue with the conference app, please create a new issue with answers to the pre-populated questions. Thanks so much!
