### ISSUE TITLE
Error: File to import not found or unreadable:

### ISSUE THREAD

**Issue by ptmagalhaes** [driftyco/ionic-conference-app#350]
**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

I see this error on browser

Error: File to import not found or unreadable: ../bower_components/ionic/scss/ionic on line 24 of app/styles/main.scss

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```
Error: File to import not found or unreadable: ../bower_components/ionic/scss/ionic on line 24 of app/styles/main.scss

@import "common";
@import "home";
@import "map";
@import "events";
@import "abstracts";
@import "schedule";

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by brandyscarney** [comment]
Thanks for the issue! I'm going to close this as it doesn't seem like it's an issue with the conference app itself. Please visit our [forum](https://forum.ionicframework.com/) or [slack channel](http://ionicworldwide.herokuapp.com/) for questions about the framework. :smile:

If this is an issue with the conference app, please create a new issue with answers to the pre-populated questions:

<img width="694" alt="screen shot 2017-01-19 at 3 19 46 pm" src="https://cloud.githubusercontent.com/assets/6577830/22123735/c61e8de4-de5a-11e6-85dd-763277b0ad86.png">

Thanks so much!
