### ISSUE TITLE
How to remove tabs menu Without broken app -- Ionic V1

### ISSUE THREAD

**Issue by ptmagalhaes** [driftyco/ionic-conference-app#353]
**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

When i remove tabs, app stop to work

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

menu.module

	.config(function($stateProvider) {
			$stateProvider
				.state('app', {
					url: '/app',
					abstract: true,
					templateUrl: 'scripts/menu/menu.html',
					controller: 'MenuController as vm',
					resolve: {
						loggedUser: ['loginSignUpService', function(loginSignUpService) {
							return loginSignUpService.getUser().isSignedIn;
						}]
					}
				})
				.state('app.tabs', {
					url: '/tab',
					templateUrl: 'scripts/menu/tabs.html',
					resolve: {
						data: function(dataService) {
							return dataService.init();
						}
					}
				});
		});

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by brandyscarney** [comment]
Thanks for the issue! I'm going to close this as it is not an issue with the conference app. Please visit our [forum](https://forum.ionicframework.com/) or [slack channel](http://ionicworldwide.herokuapp.com/) for questions about the framework. :smile:
