### ISSUE TITLE
NPM RUN BUILD fails

### ISSUE THREAD

**Issue by virtualprodigy** [driftyco/ionic-conference-app#356]
[ X] bug report

**Current behavior:**
When I attempt to run the npm run build command, I receive several errors. 

**Expected behavior:**
 From reading the documentation this should run the build scripts which will ultimately allow me to use custom webpack configs 

**Steps to reproduce:**

I cloned the repo on my machine and ran the instructions cli instructions in the project readme and served the app once[ionic serve]. Then I stopped serving and tried npm run build so I could start working on the webpack scripts and everything broke.

![screen shot 2017-01-24 at 12 41 38 pm](https://cloud.githubusercontent.com/assets/3647217/22259296/bcfae4b6-e232-11e6-9755-39a9e46c5b48.png)

**Other information:**

[npm-debug.txt](https://github.com/driftyco/ionic-conference-app/files/727470/npm-debug.txt)

**Comment by brandyscarney** [comment]
@virtualprodigy There were no errors when you ran `ionic serve`? Can you run `ionic info` and `npm ls typescript` and paste the output here? Also, if you run `ionic build` does it work?

**Comment by virtualprodigy** [comment]
@brandyscarney When I finish cloned the project, I didn't have any issues with ionic serve until I tried running npm run build. It seems like after that something broke somewhere.  I just ran ionic serve and ionic build. I'm seeing errors with both

**ionic serve output**
![screen shot 2017-01-24 at 1 13 22 pm](https://cloud.githubusercontent.com/assets/3647217/22260339/e88883f0-e236-11e6-91ca-216ef8f79336.png)

**ionic info output**
![screen shot 2017-01-24 at 1 14 11 pm](https://cloud.githubusercontent.com/assets/3647217/22260409/248bed1a-e237-11e6-9781-938f052c490c.png)

**npm ls typescript output**
![screen shot 2017-01-24 at 1 15 56 pm](https://cloud.githubusercontent.com/assets/3647217/22260443/425b4b56-e237-11e6-9dbe-2bff5263ef89.png)


**ionic build output**
*I couldn't grab a screenshot of the output*
[ionic build output.txt](https://github.com/driftyco/ionic-conference-app/files/727568/ionic.build.output.txt)

**Comment by brandyscarney** [comment]
@virtualprodigy Can you try running `rm -rf node_modues` and then a new `npm install`? It looks like something weird happened with your `npm install`. Did you update `node` or `npm` after running it?

**Comment by virtualprodigy** [comment]
I'll give that a try. I did update node after the issue started happening. My teammate suggested doing so, because he saw npm was getting a lot of peer unmet issues.

**Comment by virtualprodigy** [comment]
@brandyscarney I ran `rm -rf node_modues` and then `npm install` but it's still not installing all of the dependencies.  It won't pull es6-shim and rxjs

```
npm WARN angular2@2.0.0-beta.21 requires a peer of es6-shim@^0.35.0 but none was installed.
npm WARN angular2@2.0.0-beta.21 requires a peer of rxjs@5.0.0-beta.6 but none was installed.
```

**Comment by brandyscarney** [comment]
@virtualprodigy There was a typo in my command, first one should be `rm -rf node_modules`, sorry.

**Comment by virtualprodigy** [comment]
@brandyscarney haha I didn't even notice it. I copied and pasted...
I ran `rm -rf node_modules` and it deleted the node folder. Once I  re-running `npm install` I still saw npm fail to pull a few peers again. Is this an issue with node?  
`UNMET PEER DEPENDENCY @angular/core@2.4.4
UNMET PEER DEPENDENCY zone.js@^0.7.2
UNMET PEER DEPENDENCY es6-shim@^0.35.0
UNMET PEER DEPENDENCY reflect-metadata@0.1.2
UNMET PEER DEPENDENCY rxjs@5.0.0-beta.12
UNMET PEER DEPENDENCY zone.js@0.6.26

`

**Comment by mhartington** [comment]
whats your node and npm version? 

```
node -v
npm -v
```

**Comment by virtualprodigy** [comment]
@mhartington 
node is running v6.9.4
npm is running 4.1.1

**Comment by mhartington** [comment]
could you run 

```
sudo npm install npm@3
```

It could be an npm4 issue

**Comment by jgw96** [comment]
@virtualprodigy have you gotten a chance to try npm 3?

**Comment by lakshay23695** [comment]
I am having the exact same issue with this.

**Comment by virtualprodigy** [comment]
@jgw96 @mhartington I never downgraded my npm. Instead I created the same project in a new directory. After I did that the issue which resolved the issue.

**Comment by jgw96** [comment]
Hello all, I am going to go ahead and close this issue for now as there does not seem to be a good repro case for this issue. If anyone can come up with a solid repro case then feel free to open a new issue. Thanks!
