### ISSUE TITLE
Requested data not persisted in memory: lots of "API requests"

### ISSUE THREAD

**Issue by Sturgelose** [driftyco/ionic-conference-app#359]
**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Open the app with `ionic serve` and go to the 'schedule' page (main page). If you use the searchbox and have the DevTools enabled in your browser, you will see that for each change, RxJS does a new HTTP query to the data.json file. 
![screen shot 2017-02-15 at 3 23 09 pm](https://cloud.githubusercontent.com/assets/244191/22978510/4a2cf83a-f393-11e6-8ada-8f1db8e27ffd.png)

I'm not sure if this exactly a bug or expected functionality of the app, but as I see the, the variable `data` in `ConferenceData` provider is quite useless as it's not storing the data for future requests. This, in the end (in a real use case with an API instead of a json file) would be translated to queries to an API even if we are just filtering local data and an over usage of the internet in the phone.

**Expected behavior:**

data.json file should only be requested once at start or during intialization (well, as expected in the `load()` function), and data should be kept in memory instead of being queried every time. This seems to happen in the `processData()` function, but for some reason the data is not being saved between calls to the provider.

**Steps to reproduce:**

The actual code, just using `ionic serve`. Enable dev tools. A picture of what happens is attached in the description of the issue.

**Related code:**

```
load(): any {
    if (this.data) {
      return Observable.of(this.data);
    } else {
      return this.http.get('assets/data/data.json')
        .map(this.processData);
    }
  }
```
In this load() function, line 3 is never accessed, as for some reason this.data is not persisted between calls to the same singleton.

**Other information:**

No more info

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI:  You have been opted out of telemetry. To change this, run: cordova telemetry on.
6.5.0

Ionic Framework Version: 2.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: macOS Sierra
Node Version: v7.4.0
Xcode version: Not installed
```

**Comment by mrtnw** [comment]
This is because the this scope isn't passed to the map function. I've created a pull request which fixes this error. 

If you want to update your project yourself, update the block you posted like this:
`load(): any {
    if (this.data) {
      return Observable.of(this.data);
    } else {
      return this.http.get('assets/data/data.json')
        .map(this.processData, this);
    }
  }`

Pull request: https://github.com/driftyco/ionic-conference-app/pull/366

**Comment by brandyscarney** [comment]
Merged @mrtnw's PR, thanks again!
