### ISSUE TITLE
Popover not shown in Splitscreen mode

### ISSUE THREAD

**Issue by besi** [driftyco/ionic-conference-app#361]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
The Popover on the "About" page behind the `...` button is not shown if I watch the app in split screen on my iPad Pro (See top right corner of the app)

**Expected behavior:**
The popover is shown like it is in fulll screen

**Steps to reproduce:**
Open it on ipad
Set it to split screen
The popover disppears

![img_0173](https://cloud.githubusercontent.com/assets/160412/23091679/d800e5f2-f5bb-11e6-9f17-c08ab6c934f2.PNG)

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! This has since been fixed and will be in the next release.
