### ISSUE TITLE
add a website to a tab 

### ISSUE THREAD

**Issue by rahnamahb** [driftyco/ionic-conference-app#363]
Hi
I need to add a website to a tab (on selecting this tab).  what is the code of mytabpage (mytab.html, mytab.ts)?

see this image:
![untitled](https://cloud.githubusercontent.com/assets/24987437/23273452/4cc5e700-fa14-11e6-834f-616ae3e6d1d3.jpg)

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
