### ISSUE TITLE
how use other webview instead of crosswalk

### ISSUE THREAD

**Issue by rahnamahb** [driftyco/ionic-conference-app#364]
Hi
how i can chenge the crosswalk webview to other webviews?
& how build for any version of android?
(crosswalk makes very large .apk file.)

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
