### ISSUE TITLE
Application crash when attempting to filter sessions 

### ISSUE THREAD

**Issue by Smoke1987** [driftyco/ionic-conference-app#368]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Download master branch. Go to the directory and run npm install. Run the application with "ionic serve". Go to the page "Filter sessions" (schedule-filter page). Try to turn off any of the toggle switches.
Getting error: "EXCEPTION: Cannot read property 'detect' of undefined".

**Expected behavior:**
Correct switching toggle switches.

**Steps to reproduce:**
![Step 1](https://3.downloader.disk.yandex.ru/disk/f198639d8bdd781b48ab5214f47db58548fca41d575090893239e1aaa499a9e8/58c2d0a2/rG982TBebLyh71O3NPKFnbRj2PJGejixY2S6xVa3LEHGCOHASaS9NvE5ysI1al81uaq5wXTtOTHv-WFAo92Whw%3D%3D?uid=0&filename=1.jpg&disposition=inline&hash=&limit=0&content_type=image%2Fjpeg&fsize=168636&hid=71800bcb861eba2bd1c9c285786ef55d&media_type=image&tknv=v2&etag=ffadbb0ff551009ae0c6fe67970dca2e)

**Related code:**

```
npm install
ionic serve

```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v6.9.4
Xcode version: Not installed
```

**Comment by Smoke1987** [comment]
Hi! Does anyone have any idea how to fix this? Any suggestions now will be useful.

**Comment by brandyscarney** [comment]
@Smoke1987 Hello! I'm not able to reproduce this. Is there a specific device or browser you are seeing this in?

**Comment by Smoke1987** [comment]
@brandyscarney Hello! I solved this problem. The trouble was to expand for the browser Chrome: "TamperMonkey". Thanks for the tip-off.
