### ISSUE TITLE
App won´t build

### ISSUE THREAD

**Issue by appwrx** [driftyco/ionic-conference-app#371]
**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
App build crashes with "build dev failed: Cannot set property 'fileSystem' of null"

**Steps to reproduce:**
- clone rep and run 'serve'

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.3-201612081620
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 0.0.46
ios-deploy version: 1.9.1 
ios-sim version: 4.1.1 
OS: macOS Sierra
Node Version: v6.7.0
Xcode version: Xcode 8.2.1 Build version 8C1002

**Comment by brandyscarney** [comment]
Thanks for the issue! Could you try updating your CLI:

```
npm uninstall -g ionic
npm install -g ionic
```

and then pull down the latest and run the following commands in the project folder:

```
rm -rf node_modules/
npm install
ionic serve
```

and let me know if you're still having this error? Thanks!

**Comment by jgw96** [comment]
Hello! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
