### ISSUE TITLE
Support page Prevent issue on ionViewCanLeave()

### ISSUE THREAD

**Issue by juntaforce** [driftyco/ionic-conference-app#372]
**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
In support page When we said stay, if the supportMessage has data, it gives an promise error like that
EXCEPTION: Uncaught (in promise): false

**Expected behavior:**
No errors and  I cant handle if the user wants to leave and if I need do something before leave. Because its returns with boolean value with handle.

**Steps to reproduce:**

**Related code:**

```
ionViewCanLeave(): boolean | Promise<boolean> {
    // If the support message is empty we should just navigate
    if (!this.supportMessage || this.supportMessage.trim().length === 0) {
      return true;
    }

    return new Promise((resolve: any, reject: any) => {
      let alert = this.alertCtrl.create({
        title: 'Leave this page?',
        message: 'Are you sure you want to leave this page? Your support message will not be submitted.'
      });
      alert.addButton({ text: 'Stay', handler: reject });
      alert.addButton({ text: 'Leave', role: 'cancel', handler: resolve });

      alert.present();
    });
  }
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by Smoke1987** [comment]
Hi, **juntaforce**!! I tried to reproduce the situation for obtaining the specified exception. But at me all works correctly and without errors. The console output is triggered (in app.component.ts): 
`openPage(page:PageInterface) {`
`        // the nav component was found using @ViewChild(Nav)`
`        // reset the nav to remove previous pages and only have this page`
`        // we wouldn't want the back button to show in this scenario`
`        if (page.index) {`
`            this.nav.setRoot(page.component, {tabIndex: page.index});`
`        } else {`
`            this.nav.setRoot(page.component).catch(() => {`
                ## **console.log("Didn't set nav root");**
`            });`
`        }`

`ionic info`
Cordova CLI: 6.5.0
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v6.9.4
Xcode version: Not installed

##dependencies in `package.json`
"dependencies": {
    "@angular/common": "2.4.8",
    "@angular/compiler": "2.4.8",
    "@angular/compiler-cli": "2.4.8",
    "@angular/core": "2.4.8",
    "@angular/forms": "2.4.8",
    "@angular/http": "2.4.8",
    "@angular/platform-browser": "2.4.8",
    "@angular/platform-browser-dynamic": "2.4.8",
    "@angular/platform-server": "2.4.8",
    "@ionic/storage": "2.0.0",
    "ionic-angular": "2.2.0",
    "ionic-native": "2.4.1",
    "ionicons": "3.0.0",
    "rxjs": "5.0.1",
    "sw-toolbox": "3.4.0",
    "zone.js": "0.7.2"
  },
  "devDependencies": {
    "@ionic/app-scripts": "1.1.4",
    "typescript": "2.0.9"
  }

**Comment by brandyscarney** [comment]
I pushed a fix for this, please pull the latest code and run the following commands:

```
rm -rf node_modules
npm install
ionic serve
```

Let me know if you still it, thanks!
