### ISSUE TITLE
device status bar color

### ISSUE THREAD

**Issue by wdjjinan** [driftyco/ionic-conference-app#375]
I want to set the status bar color to black, but it always is blue on my Android mobile. dont know why, can you help me? Thanks very much!

**Comment by wdjjinan** [comment]
I have changed the primary color to black in variables.scss, but the status bar still use blue color......

**Comment by Abhith** [comment]
`this.statusBar.backgroundColorByHexString('#000000'); // set status bar to black`

More info about Status Bar [here](http://ionicframework.com/docs/v2/native/status-bar/)

**Comment by wdjjinan** [comment]
hello @Abhith 

import { StatusBar } from '@ionic-native/status-bar'; 

this line not work in the ionic-conference-app, can not find the status-bar module

Thanks

**Comment by wdjjinan** [comment]
hello guys @Abhith @mlynch @paulmeller @ericb @manucorporat 

even i use the this.statusBar.backgroundColorByHexString('#000000');  in the app.component.ts file, the status bar still show blue color, could you tell me where did you set the color?
Thanks

**Comment by Abhith** [comment]
in app.component.ts
```
import { Splashscreen, StatusBar, OneSignal } from 'ionic-native';
constructor(
    public events: Events,
    public userData: UserData,
    public menu: MenuController,
    public toastCtrl: ToastController,
    platform: Platform
  ) {
    // Call any initial plugins when ready
    platform.ready().then(() => {     
      StatusBar.backgroundColorByHexString("#004d40");
      Splashscreen.hide();
      ....
    });

   ......
  }
```

This is the working code from my app.

**Comment by suau** [comment]
If you are using XWalk, this isn't sufficient and will not work properly on first startup.
Additionally to what @Abhith suggested, you need to also open `index.html` and edit the meta tag like here:
`<meta name="theme-color" content="#4e8ef7">`

NOTE: this will also change the android-app-switcher tab color (the overview of opened apps on android)

**Comment by wdjjinan** [comment]
@suau thanks, it works

**Comment by bbbcmatsui** [comment]
@suau thanks!
