### ISSUE TITLE
Show Schedules for 2 days

### ISSUE THREAD

**Issue by SGEDA** [driftyco/ionic-conference-app#378]
i would show my schedules for 2 days
thank you

**Comment by brandyscarney** [comment]
Duplicate of https://github.com/driftyco/ionic-conference-app/issues/189, thanks!

**Comment by SGEDA** [comment]
Okey thank you i'm going to read it

**Comment by SGEDA** [comment]
plaese can you help i did not find the solution.
  <https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=aminesged@gmail.com&idSignature=22>
