### ISSUE TITLE
SideMenu is broken

### ISSUE THREAD

**Issue by aalgabre** [driftyco/ionic-conference-app#379]
The sidemenu is broken since this commit

https://github.com/driftyco/ionic-conference-app/commit/d1b0aef7d7d68f448a107c9ece7fdf47367a8862

activepage doesn't get highlighted anymore and after clicking the login page i can't go back to the schedulepage

i replaced this code 

` if (this.nav.getActiveChildNav() && page.index != undefined) {
      this.nav.getActiveChildNav().select(page.index);
      // Set the root of the nav with params if it's a tab index
    } else {
      this.nav.setRoot(page.name, params).catch((err: any) => {
        console.log("Didn't set nav root: " + err);
      });
    }`

with this code 

`if (page.index != undefined) {
      this.nav.setRoot(page.component, { tabIndex: page.index }).catch(() => {
        console.log("Didn't set nav root");
      });
      // Set the root of the nav with params if it's a tab index
    } else {
      this.nav.setRoot(page.name, params).catch((err: any) => {
        console.log("Didn't set nav root: " + err);
      });
    }`

this fixed the highlighting and the navigation issue

**Comment by brandyscarney** [comment]
Thanks for the issue! 

Note to team: I fixed this on our lazy loading branch but it needs a different implementation on master.
