### ISSUE TITLE
Ionic Conf App failed to use Ionic-Native/Googlemaps

### ISSUE THREAD

**Issue by Barathwaja** [driftyco/ionic-conference-app#380]
May I know why conference app failed to use _Ionic-native/GoogleMaps_??? and i was thinking is ionic planning anything to improvise similar to this repo - **https://github.com/airbnb/react-native-maps**

Thanks

**Comment by jgw96** [comment]
Hello, thanks for using Ionic. We currently use the web version of google maps as it was easier to set up at the time. You can definitely use the ionic native Google Maps plugin if you like!

**Comment by Barathwaja** [comment]
I tried but getting some errors.. plus is ionic having plans of improvising like tat **airbnbs react native plugin**?? and please lessen the app size. coz for simple hello world itself its taking **_3-5 MB_**..

**Comment by Barathwaja** [comment]
I tried but getting some errors.. plus is ionic having plans of improvising like tat **airbnbs react native plugin**?? and please lessen the app size. coz for simple hello world itself its taking **_3-5 MB_**..
