### ISSUE TITLE
google maps doesn't work in emulator

### ISSUE THREAD

**Issue by arjunbanker** [driftyco/ionic-conference-app#381]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

**Expected behavior:**
expect: map displays with pin

**Steps to reproduce:**
1. Clone ionic-conference-app
2. Follow setup instructions
3. "cordova add platform ios"
4. ionic build ios
5. ionic emulate ios
6. click "Map"
result: empty map display
<img width="333" alt="screen shot 2017-04-10 at 5 42 48 pm" src="https://cloud.githubusercontent.com/assets/19081/24888138/f2947a96-1e15-11e7-8c7b-9a1ea62ce1d6.png">
 screen

clean ionic conference app
also tried w/ ?apikey=<js api key> on google scripts include

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

Your system information:

Cordova CLI: 6.4.0 
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.2.4
ios-deploy version: 1.9.0 
ios-sim version: 5.0.11 
OS: macOS Sierra
Node Version: v4.4.7
Xcode version: Xcode 8.3 Build version 8E162

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!

**Comment by arjunbanker** [comment]
K, I asked in slack but didn't hear back so I posted in the forums as well. I tried again with the recently-upgraded ionic-3 compatible tree but noticing the same issue.

The strange thing is that this ionic 3 example that also uses google maps doesn't suffer from the same issue, but I'm not sure why, yet - https://github.com/danielehrhardt/Ionic-2-Google-Maps-Marker-Cluster

**Comment by arjunbanker** [comment]
(the fact that the other example is working does indicate that it may be an underlying issue in this project, or possibly the framework)

**Comment by arjunbanker** [comment]
Okay, fixed by adding &key=[..] to the google maps js include, somehow I had done this incorrectly and used &apikey=[..] which was defunct. Maybe we should add to the README?
