### ISSUE TITLE
Conference app is now Ionic 3

### ISSUE THREAD

**Issue by peterennis** [driftyco/ionic-conference-app#385]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Wrong title

**Expected behavior:**
Correct title.
Use Ionic 3 (?) or the now generic Ionic

**Steps to reproduce:**
![capture023](https://cloud.githubusercontent.com/assets/140737/25017341/34040af4-2038-11e7-9d3d-07efc84a5da6.PNG)

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by brandyscarney** [comment]
Fixed, thanks!
