### ISSUE TITLE
Click active tab-bar icon will reload current tab page

### ISSUE THREAD

**Issue by chaosuperDK** [driftyco/ionic-conference-app#393]
**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

For instance, if current active page is Schedule and the tab-bar shows the active schedule icon highlight.
Then if click the schedule icon again even it's already active, it will reload schedule page.

**Expected behavior:**

if the app's Ionic version is 2.x and angular 2.x , nothing would be happened after click an active tab-icon.

**Comment by brandyscarney** [comment]
Thanks for the issue! Are you seeing this on the master branch of the conference app? I'm not able to reproduce this.

**Comment by pixelone** [comment]
I think this is a bug with ionic and has been patched in the master branch. I also get this problem. Clicking the same icon multiple times reloads the page and eventually a black screen. Easy to duplicate on lower end devices. 

https://github.com/driftyco/ionic/pull/11084/files/a16e076c80d065e4f36c81952fa4c9b9d685fa8c

**Comment by chaosuperDK** [comment]
@brandyscarney ,Not on the master branch. I just update project as https://github.com/driftyco/ionic/blob/master/CHANGELOG.md#steps-to-upgrade instructed.

**Comment by chaosuperDK** [comment]
@pixelone , Yes, problem solved after update to the latest dependencies.
