### ISSUE TITLE
Does this app support multiple day event?

### ISSUE THREAD

**Issue by yuren1978** [driftyco/ionic-conference-app#396]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[X] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

**Comment by brandyscarney** [comment]
Thanks for the issue. It does not currently, but there is an issue open to add it here: https://github.com/driftyco/ionic-conference-app/issues/189
