### ISSUE TITLE
Incorrect display of content when the program switch tab

### ISSUE THREAD

**Issue by Smoke1987** [driftyco/ionic-conference-app#401]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Hello everybody. The problem is that there is an application in which the rootpage is tabs, with four child tabs. According to the logic of the application, the first tab should be hidden. I add to the first tab the attribute `show =" false "`, tab (on the tabbar) is hidden. Then, when the application loads, the first visible tab opens. In this tab, in the file * .ts (ie on the page that belongs to this tab) I define:
`NgAfterViewInit () {
This.app.getRootNav (). GetActiveChildNav (). Select (0);
} `
And turn on the desired, hidden tab. The problem is that the content of this tab is drawn from the very top, ignoring the page header, swam under it. 
![default](https://cloud.githubusercontent.com/assets/26324597/25888854/c4a24c56-3578-11e7-81fe-5325664fad0a.jpg)

**Expected behavior:**
Correct display of content.
![default](https://cloud.githubusercontent.com/assets/26324597/25888862/c937892a-3578-11e7-8a78-98c33984b462.jpg)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Сordova CLI: 6.5.0
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.2.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v6.9.4
Xcode version: Not installed
```

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question I will urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionic-worldwide.slack.com/messages). Thanks for using Ionic!
