### ISSUE TITLE
Incorrect use of * ngFor

### ISSUE THREAD

**Issue by Smoke1987** [driftyco/ionic-conference-app#402]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[x] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I'm trying to use * ngFor in dynamically generated HTML. Enumeration on the array does not go, there is no access to variables.
![1](https://cloud.githubusercontent.com/assets/26324597/25895491/23542a36-3591-11e7-969f-248062065bda.jpg)

**Expected behavior:**
The expected result was the same when used in an HTML file.
![2](https://cloud.githubusercontent.com/assets/26324597/25895522/4b4b42b8-3591-11e7-8bec-0a3a670918e8.jpg)

**Related code:**

```
content: `  <h5><b>${scope.shop.full_name}</b></h5>
                        <h3>${scope.shop.naimen}</h3>
                        <p>${scope.shop.shopInfo.schedule}</p>

                        <h3><b>Телефоны:</b></h3>
                        <a *ngFor="let phone of shop.shopInfo.phone" href="tel: {{phone}}">
                            {{phone}}
                        <br *ngIf="!(phone == shop.shopInfo.phone[shop.shopInfo.phone.length-1])">
                        </a>
                     `
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Сordova CLI: 6.5.0
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.2.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v6.9.4
Xcode version: Not installed
```

**Comment by brandyscarney** [comment]
Thanks for the issue! I'm going to close this as it doesn't seem like it's an issue with the conference app itself. Please visit our [forum](https://forum.ionicframework.com/) or [slack channel](http://ionicworldwide.herokuapp.com/) for questions about the framework. :smile:
