### ISSUE TITLE
Add some images of the app to the README

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic-conference-app#47]
Add some images, maybe a gif or two? Let's go crazy.

**Comment by CookieCookson** [comment]
It would be nice to see examples of the app, I do not want to upgrade my ionic installation currently but am interested to see how developments are coming along!

**Comment by brandyscarney** [comment]
@CookieCookson I added some images of the app on an iPhone 6 and a Nexus 5. :)

**Comment by Splaktar** [comment]
Looks good. This issue can be closed then?

**Comment by brandyscarney** [comment]
@Splaktar I left it open because I still want to add a gif eventually :stuck_out_tongue:

**Comment by adamdbradley** [comment]
Also, each image should be retina quality.

**Comment by brandyscarney** [comment]
Added some gifs to the README, plan to add better quality ones later on.
