### ISSUE TITLE
iOS 8.x doesn't work with a form in the ion-title

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic-conference-app#49]
The following markup breaks the app on iOS 8.x (but works on iOS 9):

```
<ion-navbar *navbar>
  <ion-title>
    <form [ng-form-model]="scheduleForm">
      <ion-segment ng-control="scheduleShowing">
        <ion-segment-button value="all">
          All
        </ion-segment-button>
        <ion-segment-button value="favorites">
          Favorites
        </ion-segment-button>
      </ion-segment>
    </form>
  </ion-title>
  <ion-nav-items secondary>
    <button (click)="openScheduleFilter()"><icon ios="funnel-outline" md="funnel"></icon></button>
  </ion-nav-items>
</ion-navbar>
```

but if we remove the form from the `ion-title` it will work (aesthetically):

```
<ion-navbar *navbar>
  <ion-title>
    <ion-segment [(ng-model)]="scheduleShowing">
      <ion-segment-button value="all">
        All
      </ion-segment-button>
      <ion-segment-button value="favorites">
        Favorites
      </ion-segment-button>
    </ion-segment>
  </ion-title>
  <ion-nav-items secondary>
    <button (click)="openScheduleFilter()"><icon ios="funnel-outline" md="funnel"></icon></button>
  </ion-nav-items>
</ion-navbar>
```

I can change the `ng-control` to `ng-model` but it doesn't update the value from the `ion-segment`. Need to investigate this further.

**Comment by tlancina** [comment]
Looks like the content is being put next to the segment on iOS 8.4 for some reason:

![image](https://cloud.githubusercontent.com/assets/804331/10643517/fc7a8c50-77e8-11e5-9f73-51a7d706f095.png)

What it should look like (iOS 9):

![image](https://cloud.githubusercontent.com/assets/804331/10643557/28ea3b32-77e9-11e5-88c7-ec845f811b0c.png)

**Comment by adamdbradley** [comment]
Why is there a form element in there? Can we do without it?

**Comment by brandyscarney** [comment]
The form element is necessary for the `ng-control`, changing it to a `ng-model` doesn't work with `ion-segment`

**Comment by brandyscarney** [comment]
This is no longer an issue for the conference app since A) we've removed the form and B) segment doesn't need to be in the title. Please reopen if you think this is something we need to handle.
