### ISSUE TITLE
ionic serve fails with the following error

### ISSUE THREAD

**Issue by vasanthns** [driftyco/ionic-conference-app#50]
Hi,

I have followed the run instructions as mentioned, and I am getting the following error on ionic serve command. I am using Windows 7 with latest Node, Cordova and Ionic versions.

$/ionic-conference-app> ionic serve
? Compiling your SASS to CSS.
 **Error: file to import not found or unreadable: ionic**
Current dir: .../ionic-conference-app/www/app/
    at Object.module.exports.renderSync (...\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\node-sass\lib\index.js:424:22)
    at Object.processSass (...\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\lib\transpile.js:163:25)
    at Object.serveV2 (...\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\lib\serve.js:72:31)
    at Object.IonicTask.run (...\AppData\Roaming\npm\node_modules\ionic\lib\ionic\serve.js:49:18)
    at Object.run (...\AppData\Roaming\npm\node_modules\ionic\lib\cli.js:98:32)
    at Object.<anonymous> (...\AppData\Roaming\npm\node_modules\ionic\bin\ionic:9:10)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)

**Comment by mhartington** [comment]
From the errror is looks like you're trying to run `ionic serve` from the www directory. Could you back up to the root of the project and run ionic serve again?

**Comment by rafaelaudy** [comment]
I have the same.
I fixed it removing:

**Comment by arun0009** [comment]
+1. I had the same issue & doing what @rafaelaudy mentioned solved my problem.

**Comment by tlancina** [comment]
What is the output of `ionic info` for you guys?

**Comment by arun0009** [comment]
<code>
 Error: file to import not found or unreadable: ionic
Current dir: /development/misc/odb-mobile2/www/app/
    at Object.module.exports.renderSync (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/node-sass/lib/index.js:424:22)
    at Object.processSass (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/v2/transpile.js:203:25)
    at Object.serve (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/v2/serve.js:51:17)
    at /usr/local/lib/node_modules/ionic/lib/ionic/serve.js:87:15
    at _fulfilled (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/ionic/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:108:17)
    at doNTCallback0 (node.js:407:9)
<code>

**Comment by vasanthns** [comment]
+1. Fix mentioned by @rafaelaudy solved my problem.

**Comment by rafaelaudy** [comment]
@tlancina Want me to open a pull request? :)

**Comment by tlancina** [comment]
The ionic-framework package recently changed its structure, so the Sass source files are in a different location.

Can you guys update your CLI (`ionic@alpha`) and delete `ionic.config.js` if it exists so that `ionic serve` will autogenerate a new one and let me know if that fixes it please?

**Comment by tlancina** [comment]
If you have already updated your CLI to latest, then the `ionic.config.js` will by default have the new path.  

If you are using an older version of `ionic-framework` you can do one of two things:
  1. Update to alpha.31 with `npm install ionic-framework`
  2. Change the `includePaths` property in `ionic.config.js`  to `['node_modules/ionic-framework/src/scss']`

**Comment by brandyscarney** [comment]
Just a warning there are known performance issues with the conference app using alpha 31. We are working on these issues. There is an issue here where I am tracking the updates: #55

**Comment by rjain15** [comment]
Changing the includePaths property, installing npm install ionic-framework moved past this error. But there are bunch of other errors

$ionic serve
∆ Compiling your SASS to CSS.
√ Sass compiled to CSS.
∆ Running postcss and autoprefixer on compiled CSS.
∆ Compiling and bundling with Webpack...

√ Using your webpack.config.js file: /Users/rjain/code/ionic-examples/i2/ionic-conference-app/webpack.config.js 
√ CSS processed to: /www/build/css/app.css 
There were some errors with webpack
multi main
Module not found: Error: Cannot resolve module 'ionic/ionic' in /Users/rjain/code/ionic-examples/i2/ionic-conference-app
resolve module ionic/ionic in /Users/rjain/code/ionic-examples/i2/ionic-conference-app
  looking for modules in /Users/rjain/code/ionic-examples/i2/ionic-conference-app/node_modules
    /Users/rjain/code/ionic-examples/i2/ionic-conference-app/node_modules/ionic doesn't exist (module as directory)
  looking for modules in /Users/rjain/code/ionic-examples/i2/ionic-conference-app/node_modules/ionic-framework/node_modules
    /Users/rjain/code/ionic-examples/i2/ionic-conference-app/node_modules/ionic-framework/node_modules/ionic doesn't exist (module as directory)
  looking for modules in /Users/rjain/node_modules
    /Users/rjain/node_modules/ionic doesn't exist (module as directory)
[/Users/rjain/code/ionic-examples/i2/ionic-conference-app/node_modules/ionic]
[/Users/rjain/code/ionic-examples/i2/ionic-conference-app/node_modules/ionic-framework/node_modules/ionic]
[/Users/rjain/node_modules/ionic]
 @ multi main,multi main
Module not found: Error: Cannot resolve module 'web-animations.min' in /Users/rjain/code/ionic-examples/i2/ionic-conference-app
resolve module web-animations.min in /Users/rjain/code/ionic-examples/i2/ionic-conference-app
  looking for modules in /Users/rjain/code/ionic-examples/i2/ionic-conference-app/node_modules
    /Users/rjain/code/ionic-examples/i2/ionic-conference-app/node_modules/web-animations.min doesn't exist (module as directory)
    resolve 'file' web-animations.min in /Users/rjain/code/ionic-examples/i2/ionic-conference-app/node_modules
      resolve file
        /Users/rjain/code/ionic-examples/i2/ionic-conference-app/node_modules/web-animations.min doesn't exist
        /Users/rjain/code/ionic-examples/i2/ionic-conference-app/node_modules/web-animations.min.ts doesn't exist
        /Users/rjain/code/ionic-examples/i2/ionic-conference-app/node_modules/web-animations.min.js doesn't exist
  looking for modules in /Users/rjain/code/ionic-examples/i2/ionic-conference-app/node_modules/ionic-framework/node_modules
    /Users/rjain/code/ionic-examples/i2/ionic-conference-app/node_modules/ionic-framework/node_modules/web-animations.min doesn't exist (module as directory)
    resolve 'file' web-animations.min in /Users/rjain/code/ionic-examples/i2/ionic-conference-app/node_modules/ionic-framework/node_modules
      resolve file
        /Users/rjain/code/ionic-examples/i2/ionic-conference-app/node_modules/ionic-framework/node_modules/web-animations.min doesn't exist
        /Users/rjain/code/ionic-examples/i2/ionic-conference-app/node_modules/ionic-framework/node_modules/web-animations.min.js doesn't exist
        /Users/rjain/code/ionic-examples/i2/ionic-conference-app/node_modules/ionic-framework/node_modules/web-animations.min.ts doesn't exist
  looking for modules in /Users/rjain/node_modules
    /Users/rjain/node_modules/web-animations.min doesn't exist (module as directory)
    resolve 'file' web-animations.min in /Users/rjain/node_modules
      resolve file
        /Users/rjain/node_modules/web-animations.min doesn't exist
        /Users/rjain/node_modules/web-animations.min.js doesn't exist
        /Users/rjain/node_modules/web-animations.min.ts doesn't exist
[/Users/rjain/code/ionic-examples/i2/ionic-conference-app/node_modules/web-animations.min]
[/Users/rjain/code/ionic-examples/i2/ionic-conference-app/node_modules/web-animations.min]
[/Users/rjain/code/ionic-examples/i2/ionic-conference-app/node_modules/web-animations.min.ts]
[/Users/rjain/code/ionic-examples/i2/ionic-conference-app/node_modules/web-animations.min.js]
[/Users/rjain/code/ionic-examples/i2/ionic-conference-app/node_modules/ionic-framework/node_modules/web-animations.min]
[/Users/rjain/code/ionic-examples/i2/ionic-conference-app/node_modules/ionic-framework/node_modules/web-animations.min]
[/Users/rjain/code/ionic-examples/i2/ionic-conference-app/node_modules/ionic-framework/node_modules/web-animations.min.js]
[/Users/rjain/code/ionic-examples/i2/ionic-conference-app/node_modules/ionic-framework/node_modules/web-animations.min.ts]
[/Users/rjain/node_modules/web-animations.min]
[/Users/rjain/node_modules/web-animations.min]
[/Users/rjain/node_modules/web-animations.min.js]
[/Users/rjain/node_modules/web-animations.min.ts]
 @ multi main,./www/app/app.js
Module build failed: Cannot resolve module 'ionic/ionic' in /Users/rjain/code/ionic-examples/i2/ionic-conference-app/www/app
    Required in /Users/rjain/code/ionic-examples/i2/ionic-conference-app/www/app/app.js
 @ multi main
 0=multi main
Module not found: Error: Cannot resolve module 'ionic/ionic' in /Users/rjain/code/ionic-examples/i2/ionic-conference-app
resolve module ionic/ionic in /Users/rjain/code/ionic-examples/i2/ionic-conference-app
  looking for modules in /Users/rjain/code/ionic-examples/i2/ionic-conference-app/node_modules
    /Users/rjain/code/ionic-examples/i2/ionic-conference-app/node_modules/ionic doesn't exist (module as directory)
  looking for modules in /Users/rjain/code/ionic-examples/i2/ionic-conference-app/node_modules/ionic-framework/node_modules
    /Users/rjain/code/ionic-examples/i2/ionic-conference-app/node_modules/ionic-framework/node_modules/ionic doesn't exist (module as directory)
  looking for modules in /Users/rjain/node_modules
    /Users/rjain/node_modules/ionic doesn't exist (module as directory)
[/Users/rjain/code/ionic-examples/i2/ionic-conference-app/node_modules/ionic]
[/Users/rjain/code/ionic-examples/i2/ionic-conference-app/node_modules/ionic-framework/node_modules/ionic]
[/Users/rjain/node_modules/ionic]
 @ multi main, 1=multi main
Module not found: Error: Cannot resolve module 'web-animations.min' in /Users/rjain/code/ionic-examples/i2/ionic-conference-app
resolve module web-animations.min in /Users/rjain/code/ionic-examples/i2/ionic-conference-app
  looking for modules in /Users/rjain/code/ionic-examples/i2/ionic-conference-app/node_modules
    /Users/rjain/code/ionic-examples/i2/ionic-conference-app/node_modules/web-animations.min doesn't exist (module as directory)
    resolve 'file' web-animations.min in /Users/rjain/code/ionic-examples/i2/ionic-conference-app/node_modules
      resolve file
        /Users/rjain/code/ionic-examples/i2/ionic-conference-app/node_modules/web-animations.min doesn't exist
        /Users/rjain/code/ionic-examples/i2/ionic-conference-app/node_modules/web-animations.min.ts doesn't exist
        /Users/rjain/code/ionic-examples/i2/ionic-conference-app/node_modules/web-animations.min.js doesn't exist
  looking for modules in /Users/rjain/code/ionic-examples/i2/ionic-conference-app/node_modules/ionic-framework/node_modules
    /Users/rjain/code/ionic-examples/i2/ionic-conference-app/node_modules/ionic-framework/node_modules/web-animations.min doesn't exist (module as directory)
    resolve 'file' web-animations.min in /Users/rjain/code/ionic-examples/i2/ionic-conference-app/node_modules/ionic-framework/node_modules
      resolve file
        /Users/rjain/code/ionic-examples/i2/ionic-conference-app/node_modules/ionic-framework/node_modules/web-animations.min doesn't exist
        /Users/rjain/code/ionic-examples/i2/ionic-conference-app/node_modules/ionic-framework/node_modules/web-animations.min.js doesn't exist
        /Users/rjain/code/ionic-examples/i2/ionic-conference-app/node_modules/ionic-framework/node_modules/web-animations.min.ts doesn't exist
  looking for modules in /Users/rjain/node_modules
    /Users/rjain/node_modules/web-animations.min doesn't exist (module as directory)
    resolve 'file' web-animations.min in /Users/rjain/node_modules
      resolve file
        /Users/rjain/node_modules/web-animations.min doesn't exist
        /Users/rjain/node_modules/web-animations.min.js doesn't exist
        /Users/rjain/node_modules/web-animations.min.ts doesn't exist
[/Users/rjain/code/ionic-examples/i2/ionic-conference-app/node_modules/web-animations.min]
[/Users/rjain/code/ionic-examples/i2/ionic-conference-app/node_modules/web-animations.min]
[/Users/rjain/code/ionic-examples/i2/ionic-conference-app/node_modules/web-animations.min.ts]
[/Users/rjain/code/ionic-examples/i2/ionic-conference-app/node_modules/web-animations.min.js]
[/Users/rjain/code/ionic-examples/i2/ionic-conference-app/node_modules/ionic-framework/node_modules/web-animations.min]
[/Users/rjain/code/ionic-examples/i2/ionic-conference-app/node_modules/ionic-framework/node_modules/web-animations.min]
[/Users/rjain/code/ionic-examples/i2/ionic-conference-app/node_modules/ionic-framework/node_modules/web-animations.min.js]
[/Users/rjain/code/ionic-examples/i2/ionic-conference-app/node_modules/ionic-framework/node_modules/web-animations.min.ts]
[/Users/rjain/node_modules/web-animations.min]
[/Users/rjain/node_modules/web-animations.min]
[/Users/rjain/node_modules/web-animations.min.js]
[/Users/rjain/node_modules/web-animations.min.ts]
 @ multi main, 2=./www/app/app.js
Module build failed: Cannot resolve module 'ionic/ionic' in /Users/rjain/code/ionic-examples/i2/ionic-conference-app/www/app
    Required in /Users/rjain/code/ionic-examples/i2/ionic-conference-app/www/app/app.js
 @ multi main

**Comment by intfrr** [comment]
The same here, if I understand it well, it looks for a directory which it never finds ionic/ionic

**Comment by tlancina** [comment]
Is this happening off a fresh `ionic start` or an existing project?

**Comment by brandyscarney** [comment]
The conference app has been updated to alpha.32, please follow the below steps to get it working:

1. Install the latest version of the Ionic CLI (currently alpha.22): `npm install -g ionic@alpha`
2. Remove & and re-download the conference app: `git clone https://github.com/driftyco/ionic-conference-app`
3. Switch into that directory and run: `npm i`

Then you should be able to run `ionic serve` and other ionic commands. Please open a new issue if you find a different problem.

**Comment by rjain15** [comment]
works after cleanup and reinstall 
````
rm -rf ionic-conference-app/
npm install -g ionic@alpha
git clone https://github.com/driftyco/ionic-conference-app
cd ionic-conference-app/
npm i
ionic serve
````
