### ISSUE TITLE
Add .jshintrc config

### ISSUE THREAD

**Issue by PCateNumbersUSA** [driftyco/ionic-conference-app#51]
It would be nice to have a default .jshintrc config to help with best practices and correcting syntax errors.

**Comment by mhartington** [comment]
Agreed, if not a jshintrc, a eslintrc file. I'll see what I can throw together

**Comment by mhartington** [comment]
Added via https://github.com/driftyco/ionic-conference-app/commit/0d4fbc34c4648b4575a4f551bb09909ea1598743
