### ISSUE TITLE
Add more Ionic components

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic-conference-app#54]
We want to show off more Ionic components, add:

- [x] grid [here](https://github.com/driftyco/ionic-conference-app/blob/master/app/pages/login/login.html#L26-L33)
- [x] side menu [here](https://github.com/driftyco/ionic-conference-app/blob/master/app/app.html#L2-L21) with following pages:
 - [x] login page [here](https://github.com/driftyco/ionic-conference-app/tree/master/app/pages/login)
 - [x] sign up page [here](https://github.com/driftyco/ionic-conference-app/tree/master/app/pages/signup)
 - [x] account page [here](https://github.com/driftyco/ionic-conference-app/tree/typescript/app/pages/account)
- [x] action sheet [here](https://github.com/driftyco/ionic-conference-app/blob/master/app/pages/speaker-list/speaker-list.js#L34-L55) ( [thanks](https://github.com/driftyco/ionic-conference-app/pull/77) )
- [x] slide box [here](https://github.com/driftyco/ionic-conference-app/tree/master/app/pages/tutorial) ( [thanks](https://github.com/driftyco/ionic-conference-app/pull/94) )
- [x] show animation [here](https://github.com/driftyco/ionic-conference-app/blob/master/app/pages/tutorial/tutorial.js#L43-L53) ( [thanks](https://github.com/driftyco/ionic-conference-app/pull/108) )
- [x] show off the config property [here](https://github.com/driftyco/ionic-conference-app/blob/master/app/app.js#L18-L23)
- [x] DateTime component [here](https://github.com/driftyco/ionic-conference-app/blob/master/app/pages/about/about.html#L20)

**Comment by brandyscarney** [comment]
Add slide box to the list

**Comment by 3dd13** [comment]
Hi @brandyscarney 


1)
What are you expecting for the side menu and slidebox ?

may I suggest the following changes:
- apps starts with slidebox style tutorial
- perhaps a "Buy Ticket" button in one of the slides
- clicking the "Start Now" button goes to schedule page
- only keep the login/signup in the sidemenu, but not showing that as the first state.

2)
related question: which features are accessible only after login ?
how about
- clicking login button set a flag in local storage, and then show logout link in sidemenu
- clicking logout remove the flag

3)
related feature showcase: how about setting up a real time chat for participants with Ionic.io Push


Cheers,
Eddie

**Comment by 3dd13** [comment]
for the slide box showcase,
how about click Buy Ticket, and let ask the user to select a ticket type ?
could be choosing between "Conference" and "Conference + 1 Day Workshop"

**Comment by brandyscarney** [comment]
@3dd13 

1) I think the slidebox being used in a tutorial format is a great use of it, thanks again for the PR. I'm thinking for now it stays simple, gives a little background on the app with the final page going to the app, or they can skip it entirely. Yes, I agree the user should be able to view the app without viewing the login or signup screen.

2) I was thinking (eventually) there will be an account page that shows the users information, signing up will capture this information and store it. Yes, that is how the login page _should_ work. 

3) This could be something we add further down the road, but we want to make sure our SDK components are functioning properly before integrating any of the Ionic platform services.

**Comment by 3dd13** [comment]
would be good to keep an eye on the following missing components once they are ready in the framework: https://github.com/driftyco/ionic2/issues/569

**Comment by 3dd13** [comment]
"add a dynamic attribute example" is already applied in schedule page:
https://github.com/driftyco/ionic-conference-app/blob/master/app/pages/schedule/schedule.html#L40

**Comment by Vinothapplife** [comment]
@brandyscarney  i have installed the this app and its loading and can see the browser. But, I have created new pages in app folder. its not at all build and display in www folder.  live reload not working. can you tell me the what changes i need to do in gulp file.
