### ISSUE TITLE
Cannot resolve module 'moment'

### ISSUE THREAD

**Issue by softBarbarian** [driftyco/ionic-conference-app#62]
I am getting following error when trying to run `ionic serve` on fresh install.
```
./www/app/components/date-format.js
Module build failed: Cannot resolve module 'moment' in /Users/adm/Dev/projects/ionic-conference-app/www/app/components
    Required in /Users/adm/Dev/projects/ionic-conference-app/www/app/components/date-format.js
 @ ./www/app/about/about.js 16:20-56 (CLI v2.0.0-alpha.23)

Your system information:

Cordova CLI: 5.0.0
Gulp version:  CLI version 3.9.0
Gulp local:  
Ionic Version: 2.0.0-alpha.31
Ionic CLI Version: 2.0.0-alpha.23
Ionic App Lib Version: 2.0.0-alpha.22
ios-deploy version: 1.7.0 
ios-sim version: 4.1.1 
OS: Mac OS X Yosemite
Node Version: v0.12.2
Xcode version: Xcode 7.0 Build version 7A220 

```

**Comment by brandyscarney** [comment]
Can you try downloading a fresh copy of the conference app, running `npm install` and then running `ionic serve` again?

The conference app is running version `2.0.0-alpha.32` of Ionic now: https://github.com/driftyco/ionic-conference-app/blob/master/package.json#L18

I've made some updates to the webpack file that need to be there to work with the CLI version you have.

**Comment by softBarbarian** [comment]
thanks @brandyscarney that worked!

**Comment by softBarbarian** [comment]
So @brandyscarney how do we get tickets to Ionic conference?

**Comment by brandyscarney** [comment]
Sorry, the conference isn't an actual thing at the moment. It is just a sample app to show off Ionic 2.0.
