### ISSUE TITLE
Make a custom app icon for the conference app

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic-conference-app#66]
We want a cool app icon. :smile:

& a splashscreen image would be nice.

**Comment by adamdbradley** [comment]
+1

+1

Any updates!?!?!

What's the status on this issue!?!?!

My boss wants this done ASAP! Plz close this!

 @bensperry

**Comment by brandyscarney** [comment]
:+1:

**Comment by adamdbradley** [comment]
+1

**Comment by bensperry** [comment]
+1

**Comment by bensperry** [comment]
[conference app icon.zip](https://github.com/driftyco/ionic-conference-app/files/80760/conference.app.icon.zip)

**Comment by adamdbradley** [comment]
You are a gentleman and a scholar.

**Comment by brandyscarney** [comment]
Reopening so I remember to add it.

**Comment by brandyscarney** [comment]
Nevermind apparently Adam already did.
