### ISSUE TITLE
Rename pages

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic-conference-app#68]
- [x] The detail page should be named the same as the list page
- [x] Rename `speakers` to `speaker-list`
- [x] Rename `sessions` to `schedule`
- [x] Rename `schedule-list` to `session-list`
- [x] Rename `filter-sessions` to `session-filter` 
- [x] Add Page back to Classes
- [ ] Update README with new names

**Comment by adamdbradley** [comment]
1. makes sense, got my vote :+1: 
2. yes
3. sure

Also, i know we all went back and forth on the `Page` suffix, but max and I finally agreed it's probably best to suffix all Page UI components with `Page`. Reason being, if you are importing both `ScheduleList` and `Schedule` components, which one is the page? Similar to how iOS would have `ScheduleViewController`. So the directory does not need to have a `-page` suffix, but JS classes that have the `@Page` decorator should always end with `Page`.

**Comment by adamdbradley** [comment]
Also to clarify, when there are two similar pages, one that lists all the "things" and one that is a detail of one "thing", then I agree we should always have `List` and `Detail`. So `SessionListPage` and `SessionDetailPage` would make sense here.

**Comment by brandyscarney** [comment]
Okay so if I'm only using the Page as a Modal should it be suffixed with Page or Modal? And then Components should be suffixed with Component? We'll need to update the generators for this.

**Comment by adamdbradley** [comment]
It should always end in Page, even if it would only be in a modal.

**Comment by adamdbradley** [comment]
Also, i'm not sure about suffixing with `Component` or `Cmp` right now. Let's put the Page suffix in and see how it it all fits together.

**Comment by brandyscarney** [comment]
Sounds good thanks!

**Comment by iammash** [comment]
hello, 
This might not be related to the issue above, but maybe someone can help me out. I am new to ionic and i would like to know how to go about renaming already created pages. For example when i create a project based on the ionic sidemenu template, i get page1 and page2 how do i rename those to my desired names.

I will appreciate any help.

**Comment by brandyscarney** [comment]
hey @iammash, you can rename the folder for the page and all files inside of it, and then update any paths that use it. For example, here: https://github.com/driftyco/ionic2-starter-sidemenu/blob/master/src/app/app.component.ts#L5

You can then change the class name and any imports if you'd like. Or you could use our generator to add a new page: http://ionicframework.com/docs/v2/cli/generate/

**Comment by iammash** [comment]
thanks @brandyscarney. I will try that again, i may have missed out changing something when I tried the last time.
