### ISSUE TITLE
Dead code in ConferenceApp constructor

### ISSUE THREAD

**Issue by dorontal** [driftyco/ionic-conference-app#74]
In the ConferenceApp's constructor, setting:

    this.loggedIn = false;

followed by this code:

    if (!this.loggedIn) {
      this.root = LoginPage;
    }

causes the if statement to always evaluate to true.

It's simpler to just have

    this.root = LoginPage;

instead of the if statement.

**Comment by brandyscarney** [comment]
Hey,

I added it as a placeholder for a future authentication service, but I can see how it can be confusing. I'll remove it and just add a comment. Thanks!
