### ISSUE TITLE
on iOS device, in Schedule tab, clicking search field and then cancel. the keyboard still stays open

### ISSUE THREAD

**Issue by 3dd13** [driftyco/ionic-conference-app#76]
here are the commands I used to run the apps

    git clone
    npm install --production
    ionic run ios --device

![img_1121](https://cloud.githubusercontent.com/assets/223555/11328575/f7d2acde-91c7-11e5-832d-765c406a8464.jpg)

**Comment by brandyscarney** [comment]
Thanks for the issue! I'll look into this tomorrow.

**Comment by brandyscarney** [comment]
So since this issue is related to the framework itself I opened an issue there: https://github.com/driftyco/ionic2/issues/640
