### ISSUE TITLE
Error when running ionic serve in conference app

### ISSUE THREAD

**Issue by gigocabrera** [driftyco/ionic-conference-app#78]
I updated to the latest version of ionic 2 and I am getting an error when I run the **ionic serve** command. 

**Please help!**

`Cordova CLI: 5.3.3`
`Gulp version: CLI version 3.8.11`
`Gulp local:`
`Ionic Version: 2.0.0-alpha.35`
`Ionic CLI Version: 2.0.0-alpha.25`
`Ionic App Lib Version: 2.0.0-alpha.24`
`OS: `
`Node Version: v5.1.0`

![ionic-conference-app-error](https://cloud.githubusercontent.com/assets/6364855/11369008/caad23ec-928a-11e5-8e81-f26fb70eec82.png)

**Comment by tlancina** [comment]
Looks like https://github.com/driftyco/ionic2/issues/528#issuecomment-157536412, if you move your project to `C:` does it work?

**Comment by gigocabrera** [comment]
@tlancina moving the project to C: works as expected. This is awesome, thank you! 

P.S. Maybe in the future you can support having the project on different drives.

**Comment by brandyscarney** [comment]
Closing this issue since it isn't related to the conference app. Please write any comments on the linked issue. Thanks. :)
