### ISSUE TITLE
ts file configuration in webpack.config.js

### ISSUE THREAD

**Issue by sjclemmy** [driftyco/ionic-conference-app#81]
Unless there is something I'm missing, in order for the webpack build process to work with .ts files as well as .js files (as is currently the case) then the `'doTypeCheck': false` query option is required for the .ts entry.
So, for files with the 'ts' ending to compile with `ionic serve` the webpack.config.js file config element;
        
      {
        test: /\.ts$/,
        loader: "awesome-typescript",
        include: [path.join(__dirname, 'www')],
        exclude: /node_modules/
      }
should actually be:

      {
        test: /\.ts$/,
        loader: "awesome-typescript",
        query: {
          'doTypeCheck': false
        },
        include: [path.join(__dirname, 'www')],
        exclude: /node_modules/
      }

**Comment by tlancina** [comment]
Hey this is a good workaround for the moment, but the real issue I believe is that `ionic serve` should still build even when it encounters type errors.  If you have webpack installed and run `webpack` it will emit type errors but still build.

I've opened an issue for this: https://github.com/driftyco/ionic2/issues/646, so I'm going to close this and track it there.
