### ISSUE TITLE
Scrollbar very unresponsive in Firefox

### ISSUE THREAD

**Issue by mpaland** [driftyco/ionic-conference-app#84]
Testing the app under Windows 10 in Firefox 42.0 via "ionic serve"

On the "schedule" page scrolling by the right scrollbar is pretty unresponsive. Using the mouse wheel is a little better.
Is this the known native scroll problem?

**Comment by andrewmcgivery** [comment]
Just tested in Windows 10, Firefox 43.0.3, not seeing any issues with scrolling.

**Comment by brandyscarney** [comment]
Thanks for testing @andrewmcgivery. This may have been fixed in a recent release. @mpaland could you see if this is still an issue and close this if not? Thanks!

**Comment by mpaland** [comment]
This can't be observed anymore.
Schedule list scroller is responsive in current version, tested with FF 43.0.2
Thanx!
