### ISSUE TITLE
clicking Cancel to close schedule filter should set the excludeTracks to original excludeTracks

### ISSUE THREAD

**Issue by 3dd13** [driftyco/ionic-conference-app#92]
in Schedule page, open filter, click "Cancel" and open filter again shows empty filters list

![screen shot 2015-12-14 at 13 51 40](https://cloud.githubusercontent.com/assets/223555/11773800/d45df936-a269-11e5-9b11-ccefd24708d2.png)

because the onClose callback parameter (excludeTracks) is undefined when user click "Cancel" to close the modal.

**Comment by brandyscarney** [comment]
Fixed by #93, thanks!
