### ISSUE TITLE
Clicking "Cancel" or "clearInput icon" does not reset the schedule sessions

### ISSUE THREAD

**Issue by 3dd13** [driftyco/ionic-conference-app#95]
## the problem

after changing the query in searchbar and then click the Cancel button or ClearInput icon (cross icon),
the sessions should show the full list of schedule, but the SchedulePage updateSchedule() is not being called to refresh the list.
right now only keyup would trigger the refresh.

![screen shot 2015-12-14 at 16 06 32](https://cloud.githubusercontent.com/assets/223555/11775787/c07859bc-a27c-11e5-8f66-300f5f304b1c.png)

## the reason

I had a look at the ionic searchbar.js, when the clearInput icon is clicked, the following code is executed without triggering any callback:

    Searchbar.prototype.clearInput = function (event) {
      this.writeValue('');
      this.onChange('');
    };

when the cancel button is clicked, the cancelAction callback is executed, however, it is in the SearchBar scope, so that there is no way to call SchedulePage updateSchedule() to update the list

    this.cancelAction && this.cancelAction(event, query);

## potential fixes

I want to fix this, but have no idea how to do it properly.

* the best way in angular1, I guess is a generic "watch" on the queryText variable.
* another way is changing the ngFor="#group of groups" to a function, so that it detects the changes of queryText variable
* next one would be emitting appropriate event / callback from ionic searchbar codebase, so that the SchedulePage class can receive it

@brandyscarney @adamdbradley @tlancina any suggestion ?

**Comment by brandyscarney** [comment]
I have been working on fixing the searchbar in the Ionic source code which will allow the user to capture the `(input)` event. This latest version of it isn't released yet, but these are the related issues:

https://github.com/driftyco/ionic2/issues/666
https://github.com/driftyco/ionic2/issues/731

Thanks for the feedback :)

**Comment by brandyscarney** [comment]
I'm going to close this because in the end it should be resolved in the source code itself, and it _should_ be resolved by the above issues.
