### ISSUE TITLE
Tabs messed up iOS 9 simulator

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic-conference-app#96]
Looking at the iOS 9.1 simulator the tabs aren't showing. No errors. The markup is there it just seems like  the tabs aren't getting selected properly. 

![screen shot 2015-12-14 at 7 59 54 pm](https://cloud.githubusercontent.com/assets/6577830/11798923/6e7024b2-a29d-11e5-9637-fba287f25f0d.png)

Chrome & Android nexus 5 device work fine.

cc @adamdbradley

**Comment by 3dd13** [comment]
have narrowed down the issue to the side menu html code

      <button ion-item *ngFor="#p of pages" (click)="openPage(p)">
        <icon item-left [name]="p.icon"></icon>
        {{p.title}}
      </button>

if I remove this few lines of code from app.html, all the tabs are rendered correctly on iOS simulator

**Comment by brandyscarney** [comment]
This isn't an issue anymore with the latest updates.
