### ISSUE TITLE
ReferenceError: Promise is not defined

### ISSUE THREAD

**Issue by massilva** [driftyco/ionic-conference-app#97]
Hi! 

I followed the getting-started tutorial:
http://ionicframework.com/docs/v2/getting-started/installation/

When I run the command: 
**ionic serve**

throw exception: 
**ReferenceError: Promise is not defined**

And crash the layout.
The same happens when I tested the app:
https://github.com/driftyco/ionic-conference-app

How I fix it?
tk

**Comment by brandyscarney** [comment]
Since it is happening to you for all v2 apps I am going to close the issue here and we can work on fixing it over there: https://github.com/driftyco/ionic2/issues/752
